In [1]:
import numpy as np

In [36]:
# 1차원 array1 생성
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

# 2차원 array2 생성 (2행 3열)
array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

# 2차원 array3 생성 (1행 3열)
array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [37]:
# ndim으로 각 array의 차원 수 확인
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


In [39]:
# 리스트와 ndarray의 타입 비교
list1 = [1, 2, 3]
print(type(list1))

# 리스트를 ndarray로 변환
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [38]:
# int + string 혼합 리스트 → ndarray 변환 시 string으로 upcasting
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

# int + float 혼합 리스트 → ndarray 변환 시 float으로 upcasting
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [6]:
# int 배열을 astype()으로 float64로 변환
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

# float64를 int32로 변환
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

# 소수점이 있는 float을 int32로 변환하면 소수점 버림
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [7]:
# arange()로 0부터 9까지 1차원 ndarray 생성
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [8]:
# zeros()로 0으로 채워진 (3, 2) 배열 생성
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

# ones()로 1로 채워진 (3, 2) 배열 생성 (기본 dtype은 float64)
one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [9]:
# reshape()으로 1차원 배열을 다양한 형태로 변환
array1 = np.arange(10)
print('array1:\n', array1)

# (2, 5) 형태로 변환
array2 = array1.reshape(2, 5)
print('array2:\n', array2)

# (5, 2) 형태로 변환
array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [42]:
# 원소 수가 맞지 않으면 reshape() 시 ValueError 발생
array1 = np.arange(10)
array2 = array1.reshape(4, 3)  # 10개짜리를 4x3(=12)으로 → 오류

ValueError: cannot reshape array of size 10 into shape (4,3)

In [11]:
# -1 인자를 사용하면 나머지 축 크기를 자동으로 계산
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)  # 행 자동 계산 → (2, 5)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5, -1)  # 열 자동 계산 → (5, 2)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [41]:
# -1을 써도 나눠떨어지지 않으면 오류 발생
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)  # 10을 4로 나누면 나머지가 남음 → 오류

ValueError: cannot reshape array of size 10 into shape (4)

In [13]:
# 3차원 ndarray 생성
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

# 3차원을 2차원 (n, 1) 형태로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원을 2차원 (n, 1) 형태로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [14]:
# 1부터 9까지 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

# index는 0부터 시작 → array1[2]는 3번째 위치의 값
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [15]:
# 음수 인덱스: -1은 맨 마지막, -2는 뒤에서 두 번째
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [16]:
# 인덱스를 통해 특정 위치 값 수정
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [17]:
# 1차원을 3x3 2차원으로 변환 후 각 위치 값 추출
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1])
print('(row=1, col=0) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [18]:
# 슬라이싱으로 연속된 구간 추출
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]  # 0번 인덱스부터 2번 인덱스까지
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [19]:
array1 = np.arange(start=1, stop=10)

# 처음부터 세 번째까지
array4 = array1[:3]
print(array4)

# 네 번째부터 끝까지
array5 = array1[3:]
print(array5)

# 전체 추출
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [20]:
# 2차원 배열 슬라이싱: [행 범위, 열 범위]
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])


array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [21]:
# 2차원 배열에서 행 인덱스만으로 한 행 전체 추출
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [22]:
# 팬시 인덱싱: 리스트로 원하는 인덱스 위치 지정해서 추출
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

# 0행, 1행의 2열 값만 추출
array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] =>', array3.tolist())

# 0행, 1행의 0~1열 추출
array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2] =>', array4.tolist())

# 0행, 1행 전체 추출
array5 = array2d[[0, 1]]
print('array2d[[0, 1]] =>', array5.tolist())

array2d[[0, 1], 2] => [3, 6]
array2d[[0, 1], 0:2] => [[1, 2], [4, 5]]
array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


In [23]:
# 불린 인덱싱: 조건식으로 True인 위치의 값만 추출
array1d = np.arange(start=1, stop=10)
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [24]:
# 조건식을 적용하면 True/False 배열 반환
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [25]:
# True/False 배열을 직접 인덱스로 사용
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [26]:
# 위와 동일한 결과: 정수 인덱스로 직접 지정해서 추출
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


In [27]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)

# np.sort(): 원본 유지, 정렬된 새 배열 반환
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

# ndarray.sort(): 원본 자체를 정렬, 반환값은 None
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [28]:
# 내림차순 정렬: 오름차순 정렬 후 [::-1]로 뒤집기
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [29]:
array2d = np.array([[8, 12],
                    [7, 1]])

# axis=0: 행(로우) 방향으로 정렬 → 각 열 내에서 위아래 비교
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

# axis=1: 열(칼럼) 방향으로 정렬 → 각 행 내에서 좌우 비교
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [30]:
# argsort(): 정렬했을 때 각 원소가 원본에서 몇 번 인덱스였는지 반환
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [31]:
# 내림차순 argsort
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [32]:
# argsort 활용: 성적 순으로 학생 이름 정렬
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

# 성적 오름차순 정렬 시 인덱스 반환
sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)

# 해당 인덱스로 이름 배열도 같이 정렬
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [33]:
# 행렬 내적: np.dot(A, B)
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [34]:
# 전치 행렬: np.transpose(A) → 행과 열을 바꿈
A = np.array([[1, 2],
              [3, 4]])

transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
