## 넘파이 ndarray 개요

In [1]:
# numpy 라이브러리를 np라는 이름으로 불러오기 
import numpy as np 

In [2]:
array1 = np.array([1,2,3]) # array의 인자로는 리스트가 들어감 -> 리스트는 대괄호로 표현됨
print('array1 type:',type(array1)) # array 1은 numpy 배열임 -> 그러니 numpy.ndarray
print('array1 array 형태:',array1.shape) # 3개의 원소가 있는 1차원 배열 -> (3,)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2)) # array 2는 numpy 배열임 -> 그러니 numpy.ndarray
print('array2 array 형태:',array2.shape) # 2개의 행과 3개의 열이 있는 2차원 배열 -> (2, 3)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3)) # array 3은 numpy 배열임 -> 그러니 numpy.ndarray
print('array3 array 형태:',array3.shape) # 1개의 행과 3개의 열이 있는 2차원 배열 -> (1, 3)
# 위의 array3과 array1은 들어있는 숫자의 개수는 같지만 엄연히 다른 형태의 배열이다.
# 이는 괄호 개수로도 확인 가능하다.

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,array2.ndim,array3.ndim))
# array2와 array3는 모두 2차원 배열이다.
# 하지만 array2는 행이 2개이고, array3는 행이 1개인 2차원 배열이다.

array1: 1차원, array2: 2차원, array3: 2차원


In [4]:
list1 = [1,2,3] 
print(type(list1)) # list1은 리스트임 -> 그러니 list
array1 = np.array(list1) # 리스트를 인자로 넣어 numpy 배열로 변환
print(type(array1)) # array1은 numpy 배열임 -> 그러니 numpy.ndarray
print(array1, array1.dtype) # array1의 원소는 모두 정수이므로 dtype은 int

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [5]:
list2 = [1, 2, 'test'] # <= 리스트는 서로 다른 자료형이 섞여있기 가능
array2 = np.array(list2) # 하지만, numpy 배열은 모두 같은 자료형이어야 함.
print(array2, array2.dtype) # array2의 원소는 모두 문자열로 변환되어 나온다!

list3 = [1, 2, 3.0] # <= 이번엔 정수 + 실수로 구성된 리스트
array3 = np.array(list3) #
print(array3, array3.dtype) # array3의 원소는 모두 실수로 변환되어 나온다!

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [6]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64') # -> numpy의 타입변경은 astype() 메서드를 이용하기
print(array_float, array_float.dtype) # 정수 -> 실수로 변환되어 나온다!

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype) # 실수 -> 정수로 변환되어 나온다!

array_float1 = np.array([1.1, 2.1, 3.1]) # 실수 배열
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype) # 실수 -> 정수로 변환되어 나온다!


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


## ndarray를 편리하게 생성하기 - arange, zeros, ones

In [7]:
sequence_array = np.arange(10) # -> 0 포함 10 미만의 정수들로 이루어진 1차원 배열 생성
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [8]:
zero_array = np.zeros((3,2),dtype='int32') # 모든 원소가 0인 3행 2열의 정수형 배열 생성
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2)) # 모든 원소가 1인 3행 2열의 실수형 배열 생성 
print(one_array)
print(one_array.dtype, one_array.shape) #-> dtype을 지정하지 않으면 기본적으로 실수형이 된다.

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## reshape()

In [9]:
array1 = np.arange(10) # -> 0부터 9까지의 정수로 이루어진 1차원 배열 생성
print('array1:\n', array1)

array2 = array1.reshape(2,5) # -> 10개의 원소를 2행 5열로 변환
print('array2:\n',array2)

array3 = array1.reshape(5,2) # -> 10개의 원소를 5행 2열로 변환
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
array1.reshape(4,3) # 오류가 나는 이유 -> 10개의 원소를 4행 3열로 변환하려고 하는데, 
# 4*3=12이므로 원소의 개수가 맞지 않아서 오류가 난다.

ValueError: cannot reshape array of size 10 into shape (4,3)

In [11]:
array1 = np.arange(10) # -> 0부터 9까지의 정수로 이루어진 1차원 배열 생성
print(array1)

array2 = array1.reshape(-1,5) # -> -1은 자동으로 계산해줌. 열이 5개이므로 행은 2개로 자동 계산
print('array2 shape:',array2.shape) # -> (2, 5)

array3 = array1.reshape(5,-1) # -> 행이 5개이므로 열은 2개로 자동 계산
print('array3 shape:',array3.shape) # -> (5, 2)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [12]:
array1 = np.arange(10) # -> 10개의 원소
array4 = array1.reshape(-1,4) # -> 열이 4개인데 10은 4로 나누어떨어지지 않으므로 에러 발생!

ValueError: cannot reshape array of size 10 into shape (4)

In [13]:
array1 = np.arange(8) # -> 0부터 7까지의 정수로 이루어진 1차원 배열 생성 (8개의 원소)
array3d = array1.reshape((2,2,2)) # -> 8개의 원소를 2x2x2 3차원 배열로 변환
print('array3d:\n',array3d.tolist()) # tolist() 메서드로 리스트 형태로 출력

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1) # -> 3차원 배열을 2차원 배열로 변환. 열이 1개이므로 행은 8개로 자동 계산
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape) # -> (8, 1)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1) # -> 1차원 배열을 2차원 배열로 변환. 열이 1개이므로 행은 8개로 자동 계산
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape) # -> (8, 1)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


## indexing

In [14]:
array1 = np.arange(start=1, stop=10) # -> 1부터 9까지의 정수로 이루어진 1차원 배열 생성
print('array1:',array1)
value = array1[2] # -> 인덱스 2번째 값을 가져오기 (3번째 원소)
print('value:',value) # -> 3이 출력됨
print(type(value)) # -> numpy의 정수형 타입 

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [15]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2]) # -> 음수 인덱스로 뒤에서부터 접근 가능

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [16]:
array1[0] = 9 # -> 인덱스 0번째 값을 9로 변경
array1[8] = 0 # -> 인덱스 8번째 값을 0으로 변경
print('array1:',array1) # -> 수정된 배열 출력

array1: [9 2 3 4 5 6 7 8 0]


In [17]:
array1d = np.arange(start=1, stop=10) # -> 1부터 9까지의 정수로 이루어진 1차원 배열 생성
array2d = array1d.reshape(3,3) # -> 9개의 원소를 3행 3열의 2차원 배열로 변환
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] ) # -> [행, 열] 형태로 접근. 첫 번째 값
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] ) # -> 0행 1열의 값
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] ) # -> 1행 0열의 값
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] ) # -> 2행 2열의 값 (마지막 값)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


In [18]:
array1 = np.arange(start=1, stop=10) # -> 1부터 9까지의 정수로 이루어진 1차원 배열 생성
array3 = array1[0:3] # -> 슬라이싱: 0번 인덱스부터 3번 인덱스 전까지 (0, 1, 2번째 원소)
print(array3) # -> [1 2 3] 출력됨
print(type(array3)) # -> 슬라이싱 결과도 numpy.ndarray 타입

[1 2 3]
<class 'numpy.ndarray'>


In [19]:
array1 = np.arange(start=1, stop=10) # -> 1부터 9까지의 정수로 이루어진 1차원 배열 생성
array4 = array1[:3] # -> 처음부터 3번 인덱스 전까지 (0, 1, 2번째 원소)
print(array4) # -> [1 2 3]

array5 = array1[3:] # -> 3번 인덱스부터 끝까지 (3, 4, 5, 6, 7, 8번째 원소)
print(array5) # -> [4 5 6 7 8 9]

array6 = array1[:] # -> 처음부터 끝까지 전체 복사
print(array6) # -> [1 2 3 4 5 6 7 8 9]

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [20]:
array1d = np.arange(start=1, stop=10) # -> 1부터 9까지의 정수로 이루어진 1차원 배열 생성
array2d = array1d.reshape(3,3) # -> 3행 3열의 2차원 배열로 변환
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2]) # -> 0~1행, 0~1열 추출 (2x2 배열)
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3]) # -> 1~2행, 0~2열 추출 (2x3 배열)
print('array2d[1:3, :] \n', array2d[1:3, :]) # -> 1~2행, 전체 열 추출 (2x3 배열)
print('array2d[:, :] \n', array2d[:, :]) # -> 전체 행, 전체 열 추출 (전체 배열)
print('array2d[:2, 1:] \n', array2d[:2, 1:]) # -> 0~1행, 1~2열 추출 (2x2 배열)
print('array2d[:2, 0] \n', array2d[:2, 0]) # -> 0~1행, 0열만 추출 (1차원 배열로 반환됨)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [21]:
print(array2d[0]) # -> 0번째 행 전체 출력 (1차원 배열로 반환)
print(array2d[1]) # -> 1번째 행 전체 출력 (1차원 배열로 반환)
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape ) # -> 각 행의 shape는 (3,)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [22]:
array1d = np.arange(start=1, stop=10) # -> 1부터 9까지의 정수로 이루어진 1차원 배열 생성
array2d = array1d.reshape(3,3) # -> 3행 3열의 2차원 배열로 변환

array3 = array2d[[0,1], 2] # -> 팬시 인덱싱: 0행과 1행의 2열 값만 추출 (1차원 배열)
print('array2d[[0,1], 2] => ',array3.tolist()) # -> [3, 6]

array4 = array2d[[0,1], 0:2] # -> 0행과 1행의 0~1열 추출 (2x2 배열)
print('array2d[[0,1], 0:2] => ',array4.tolist()) # -> [[1, 2], [4, 5]]

array5 = array2d[[0,1]] # -> 0행과 1행 전체를 추출 (2x3 배열)
print('array2d[[0,1]] => ',array5.tolist()) # -> [[1, 2, 3], [4, 5, 6]]

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


In [23]:
array1d = np.arange(start=1, stop=10) # -> 1부터 9까지의 정수로 이루어진 1차원 배열 생성
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5] # -> 5보다 큰 원소만 추출하는 불린 인덱싱
print('array1d > 5 불린 인덱싱 결과 값 :', array3) # -> [6 7 8 9]

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [24]:
array1d > 5 # -> 각 원소가 5보다 큰지 비교한 불린 배열 반환 (True/False로 이루어진 배열)

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True]) # <= 불린 배열 직접 생성
array3 = array1d[boolean_indexes] # -> True인 위치의 원소만 추출
print('불린 인덱스로 필터링 결과 :', array3) # -> [6 7 8 9] (뒤의 4개 원소만 추출됨)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [ ]:
indexes = np.array([5,6,7,8]) # <= 추출하고 싶은 인덱스들을 배열로 만들기
array4 = array1d[ indexes ] # -> 해당 인덱스의 원소들만 추출 (팬시 인덱싱)
print('일반 인덱스로 필터링 결과 :',array4) # -> [6 7 8 9]

일반 인덱스로 필터링 결과 : [6 7 8 9]


## 행렬의 정렬, sort( )와 argsort( )

In [ ]:
org_array = np.array([ 3, 1, 9, 5]) # <= 정렬되지 않은 배열 생성
print('원본 행렬:', org_array)
# np.sort( )로 정렬 
sort_array1 = np.sort(org_array) # -> np.sort()는 원본을 유지하고 정렬된 배열을 반환
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) # -> [1 3 5 9] 오름차순 정렬됨
print('np.sort( ) 호출 후 원본 행렬:', org_array) # -> [3 1 9 5] 원본은 변경되지 않음
# ndarray.sort( )로 정렬
sort_array2 = org_array.sort() # -> ndarray.sort()는 원본 자체를 정렬하고 None을 반환
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2) # -> None
print('org_array.sort( ) 호출 후 원본 행렬:', org_array) # -> [1 3 5 9] 원본이 정렬됨


원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [ ]:
sort_array1_desc = np.sort(org_array)[::-1] # -> 오름차순 정렬 후 [::-1]로 역순 정렬 (내림차순)
print ('내림차순으로 정렬:', sort_array1_desc) # -> [9 5 3 1]

내림차순으로 정렬: [9 5 3 1]


In [ ]:
array2d = np.array([[8, 12], 
                   [7, 1 ]]) # <= 2행 2열의 2차원 배열 생성

sort_array2d_axis0 = np.sort(array2d, axis=0) # -> axis=0은 행 방향(세로)으로 정렬. 각 열마다 정렬됨
print('로우 방향으로 정렬:\n', sort_array2d_axis0) # -> [[7, 1], [8, 12]]

sort_array2d_axis1 = np.sort(array2d, axis=1) # -> axis=1은 열 방향(가로)으로 정렬. 각 행마다 정렬됨
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1) # -> [[8, 12], [1, 7]]

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [ ]:
org_array = np.array([ 3, 1, 9, 5]) # <= 정렬되지 않은 배열
sort_indices = np.argsort(org_array) # -> 정렬된 배열의 원본 인덱스를 반환 (값이 아닌 인덱스를 반환)
print(type(sort_indices)) # -> numpy.ndarray
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices) # -> [1 0 3 2] (1→3→5→9 순서의 원본 인덱스)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [ ]:
org_array = np.array([ 3, 1, 9, 5]) # <= 정렬되지 않은 배열
sort_indices_desc = np.argsort(org_array)[::-1] # -> argsort() 결과를 [::-1]로 역순 정렬 (내림차순)
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc) # -> [2 3 0 1] (9→5→3→1 순서의 원본 인덱스)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [ ]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel']) # <= 이름 배열
score_array= np.array([78, 95, 84, 98, 88]) # <= 점수 배열

sort_indices_asc = np.argsort(score_array) # -> 점수를 오름차순 정렬했을 때의 인덱스
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc) # -> [0 2 4 1 3] (78→84→88→95→98)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc]) # -> 팬시 인덱싱으로 이름을 성적순으로 출력

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


## 선형대수 연산 – 행렬 내적과 전치 행렬 구하기

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]]) # -> 2행 3열의 행렬 A
B = np.array([[7, 8],
              [9, 10],
              [11, 12]]) # -> 3행 2열의 행렬 B

dot_product = np.dot(A, B) # -> 행렬의 내적(곱셈) 계산. A(2x3) * B(3x2) = 결과(2x2)
print('행렬 내적 결과:\n', dot_product) # -> [[58, 64], [139, 154]]

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [ ]:
A = np.array([[1, 2],
              [3, 4]]) # -> 2행 2열의 행렬 A
transpose_mat = np.transpose(A) # -> 전치 행렬: 행과 열을 바꾼 행렬 (A의 i행 j열 -> 전치의 j행 i열)
print('A의 전치 행렬:\n', transpose_mat) # -> [[1, 3], [2, 4]]

A의 전치 행렬:
 [[1 3]
 [2 4]]


## Pandas 시작- 파일을 DataFrame 로딩, 기본 API

In [25]:
import pandas as pd # -> pandas 라이브러리를 pd라는 이름으로 불러오기

In [30]:
titanic_df = pd.read_csv('train.csv') # -> CSV 파일을 DataFrame으로 읽어오기
print('titanic 변수 type:',type(titanic_df)) # -> titanic_df의 타입 확인 (pandas.DataFrame)
titanic_df # -> DataFrame 전체 출력


titanic 변수 type: <class 'pandas.core.frame.DataFrame'>


,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [31]:
titanic_df.head(3) # -> DataFrame의 처음 3개 행만 출력하기

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S


In [32]:
print('DataFrame 크기: ', titanic_df.shape) # -> shape 속성으로 DataFrame의 행과 열 개수 확인 (행, 열)

DataFrame 크기:  (891, 12)


In [33]:
titanic_df.info() # -> DataFrame의 전반적인 정보 출력 (컬럼명, Non-Null 개수, 데이터 타입 등)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [34]:
titanic_df.describe() # -> 수치형 컬럼들의 통계 정보 출력 (평균, 표준편차, 최소/최대값, 사분위수 등)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [35]:
value_counts = titanic_df['Pclass'].value_counts() # -> 'Pclass' 컬럼의 각 값이 몇 개씩 있는지 카운트
print(value_counts) # -> 값별 개수를 내림차순으로 출력

Pclass
3    491
1    216
2    184
Name: count, dtype: int64


In [36]:
titanic_pclass = titanic_df['Pclass'] # -> DataFrame에서 한 개의 컬럼만 추출하면 Series 객체가 됨
print(type(titanic_pclass)) # -> pandas.Series 타입

<class 'pandas.core.series.Series'>


In [37]:
titanic_pclass.head() # -> Series의 처음 5개 값만 출력 (디폴트는 5개)

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [38]:
value_counts = titanic_df['Pclass'].value_counts() # -> value_counts()의 반환값도 Series 객체
print(type(value_counts)) # -> pandas.Series 타입
print(value_counts)

<class 'pandas.core.series.Series'>
Pclass
3    491
1    216
2    184
Name: count, dtype: int64


In [39]:
print('titanic_df 데이터 건수:', titanic_df.shape[0])
print('기본 설정인 dropna=True로 value_counts()')
# value_counts()는 디폴트로 dropna=True이므로 value_counts(dropna=True)와 동일.
print(titanic_df['Embarked'].value_counts())
print(titanic_df['Embarked'].value_counts(dropna=False))

titanic_df 데이터 건수: 891
기본 설정인 dropna=True로 value_counts()
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64


## DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환

In [40]:
import numpy as np

col_name1=['col1'] # -> 컬럼명 리스트 생성
list1 = [1, 2, 3] # -> 1차원 리스트 생성
array1 = np.array(list1) # -> 리스트를 numpy 배열로 변환
print('array1 shape:', array1.shape ) # -> (3,) 1차원 배열
# 리스트를 이용해 DataFrame 생성.
df_list1 = pd.DataFrame(list1, columns=col_name1) # -> 1차원 리스트를 DataFrame으로 변환 (3행 1열)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)
# 넘파이 ndarray를 이용해 DataFrame 생성.
df_array1 = pd.DataFrame(array1, columns=col_name1) # -> 1차원 ndarray를 DataFrame으로 변환 (3행 1열)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)

array1 shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3


In [41]:
# 3개의 칼럼명이 필요함.
col_name2=['col1', 'col2', 'col3'] # -> 3개의 컬럼명 리스트 생성

# 2행x3열 형태의 리스트와 ndarray 생성한 뒤 이를 DataFrame으로 변환.
list2 = [[1, 2, 3],
         [11, 12, 13]] # -> 2차원 리스트 생성 (2행 3열)
array2 = np.array(list2) # -> 리스트를 numpy 배열로 변환
print('array2 shape:', array2.shape ) # -> (2, 3) 2차원 배열
df_list2 = pd.DataFrame(list2, columns=col_name2) # -> 2차원 리스트를 DataFrame으로 변환 (2행 3열)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)
df_array2 = pd.DataFrame(array2, columns=col_name2) # -> 2차원 ndarray를 DataFrame으로 변환 (2행 3열)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)

array2 shape: (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13


In [42]:
# Key는 컬럼명으로 매핑, Value는 리스트 형(또는 ndarray)
dict = {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]} # -> 딕셔너리 생성. Key가 컬럼명, Value가 각 컬럼의 값
df_dict = pd.DataFrame(dict) # -> 딕셔너리를 DataFrame으로 변환 (2행 3열)
print('딕셔너리로 만든 DataFrame:\n', df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33


In [43]:
# DataFrame을 ndarray로 변환
array3 = df_dict.values # -> DataFrame의 values 속성으로 numpy ndarray로 변환
print('df_dict.values 타입:', type(array3), 'df_dict.values shape:', array3.shape) # -> numpy.ndarray, (2, 3)
print(array3) # -> [[1 2 3] [11 22 33]]



df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]


In [44]:
# DataFrame을 리스트로 변환
list3 = df_dict.values.tolist() # -> DataFrame을 ndarray로 변환한 후 tolist()로 리스트로 변환
print('df_dict.values.tolist() 타입:', type(list3)) # -> list 타입
print(list3) # -> [[1, 2, 3], [11, 22, 33]]

# DataFrame을 딕셔너리로 변환
dict3 = df_dict.to_dict('list') # -> DataFrame을 딕셔너리로 변환. 'list' 옵션: 각 컬럼을 리스트로 변환
print('\n df_dict.to_dict() 타입:', type(dict3)) # -> dict 타입
print(dict3) # -> {'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

df_dict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict() 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


## DataFrame의 컬럼 데이터 셋 Access

In [45]:
titanic_df['Age_0']=0 # -> DataFrame에 새로운 컬럼 'Age_0'을 추가하고 모든 값을 0으로 설정
titanic_df.head(3) # -> 처음 3개 행 출력하여 확인

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0


In [46]:
titanic_df['Age_by_10'] = titanic_df['Age']*10 # -> 'Age' 컬럼의 값에 10을 곱한 새로운 컬럼 'Age_by_10' 생성
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch']+1 # -> 형제자매 수 + 부모/자녀 수 + 1로 가족 수 계산
titanic_df.head(3) # -> 처음 3개 행 출력하여 확인

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,220.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,380.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,260.0,1


In [47]:
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100 # -> 기존 컬럼 'Age_by_10'의 모든 값에 100을 더하기
titanic_df.head(3) # -> 처음 3개 행 출력하여 확인

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1


## DataFrame 데이터 삭제

In [48]:
titanic_drop_df = titanic_df.drop('Age_0', axis=1 ) # -> 'Age_0' 컬럼 삭제. axis=1은 컬럼 방향, inplace=False가 디폴트라 원본은 유지
titanic_drop_df.head(3) # -> 새로운 DataFrame에서는 'Age_0' 컬럼이 없음

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,360.0,1


In [49]:
titanic_df.head(3) # -> 원본 DataFrame은 변경되지 않았으므로 'Age_0' 컬럼이 여전히 존재

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1


In [50]:
drop_result = titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis=1, inplace=True) # -> 3개 컬럼 삭제. inplace=True라 원본이 변경됨
print(' inplace=True 로 drop 후 반환된 값:',drop_result) # -> inplace=True일 때는 None을 반환
titanic_df.head(3) # -> 원본 DataFrame에서 3개 컬럼이 삭제되었음

 inplace=True 로 drop 후 반환된 값: None


,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S


In [51]:
pd.set_option('display.width', 1000) # -> pandas 출력 설정: 한 줄에 표시할 최대 너비
pd.set_option('display.max_colwidth', 15) # -> 각 컬럼의 최대 표시 너비를 15로 설정
print('#### before axis 0 drop ####')
print(titanic_df.head(3)) # -> 삭제 전 처음 3개 행 출력

titanic_df.drop([0,1,2], axis=0, inplace=True) # -> 인덱스 0, 1, 2번 행 삭제. axis=0은 행 방향

print('#### after axis 0 drop ####')
print(titanic_df.head(3)) # -> 삭제 후 처음 3개 행 출력 (이제 인덱스 3, 4, 5가 보임)

#### before axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
#### after axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q


## Index 객체

In [53]:
# 원본 파일 재 로딩 
titanic_df = pd.read_csv('train.csv') # -> CSV 파일을 다시 읽어서 원본 상태로 복원
# Index 객체 추출
indexes = titanic_df.index # -> DataFrame의 인덱스 객체 추출
print(indexes) # -> RangeIndex(start=0, stop=891, step=1) 형태로 출력됨
# Index 객체를 실제 값 arrray로 변환 
print('Index 객체 array값:\n',indexes.values) # -> 인덱스를 numpy array로 변환하여 출력


RangeIndex(start=0, stop=891, step=1)
Index 객체 array값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232

In [54]:
print(type(indexes.values)) # -> numpy.ndarray 타입
print(indexes.values.shape) # -> (891,) 1차원 배열
print(indexes[:5].values) # -> 처음 5개 인덱스를 슬라이싱하여 array로 변환
print(indexes.values[:5]) # -> array를 슬라이싱. 위와 동일한 결과
print(indexes[6]) # -> 6번째 인덱스 값 출력 (정수 6)

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


In [55]:
indexes[0] = 5 # -> Index 객체는 변경 불가능하므로 이 코드는 에러 발생! (TypeError)

TypeError: Index does not support mutable operations

In [56]:
series_fair = titanic_df['Fare'] # -> 'Fare' 컬럼을 Series로 추출
print('Fair Series max 값:', series_fair.max()) # -> Series의 최댓값 (가장 비싼 요금)
print('Fair Series sum 값:', series_fair.sum()) # -> Series의 합계
print('sum() Fair Series:', sum(series_fair)) # -> 파이썬 내장 sum() 함수로도 합계 계산 가능
print('Fair Series + 3:\n',(series_fair + 3).head(3) ) # -> 모든 요금에 3을 더한 후 처음 3개만 출력

Fair Series max 값: 512.3292
Fair Series sum 값: 28693.9493
sum() Fair Series: 28693.9493
Fair Series + 3:
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64


In [57]:
titanic_reset_df = titanic_df.reset_index(inplace=False) # -> 인덱스를 0부터 시작하는 정수로 재설정. 기존 인덱스는 'index' 컬럼으로 추가됨
titanic_reset_df.head(3) # -> 새로운 DataFrame 확인. 'index' 컬럼이 생겼음

,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr....",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mr...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, ...",female,26.0,0,0,STON/O2. 31...,7.9250,NaN,S


In [58]:
print('### before reset_index ###')
value_counts = titanic_df['Pclass'].value_counts() # -> 'Pclass' 값별 개수를 Series로 반환
print(value_counts) # -> 인덱스가 Pclass 값(3, 1, 2), 값이 개수인 Series
print('value_counts 객체 변수 타입:',type(value_counts)) # -> pandas.Series

new_value_counts = value_counts.reset_index(inplace=False) # -> Series를 DataFrame으로 변환. 인덱스가 'index' 컬럼이 됨
print('### After reset_index ###')
print(new_value_counts) # -> 2개 컬럼을 가진 DataFrame이 됨
print('new_value_counts 객체 변수 타입:',type(new_value_counts)) # -> pandas.DataFrame

### before reset_index ###
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
value_counts 객체 변수 타입: <class 'pandas.core.series.Series'>
### After reset_index ###
   Pclass  count
0       3    491
1       1    216
2       2    184
new_value_counts 객체 변수 타입: <class 'pandas.core.frame.DataFrame'>


## 데이터 셀렉션 및 필터링

In [59]:
print('단일 컬럼 데이터 추출:\n', titanic_df[ 'Pclass' ].head(3)) # -> DataFrame에서 한 개의 컬럼만 추출 (대괄호 1개)
print('\n여러 컬럼들의 데이터 추출:\n', titanic_df[ ['Survived', 'Pclass'] ].head(3)) # -> 여러 컬럼 추출 (대괄호 2개)
print('[ ] 안에 숫자 index는 KeyError 오류 발생:\n', titanic_df[0]) # -> 숫자 인덱스로 직접 접근하면 에러 발생!

단일 컬럼 데이터 추출:
 0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 컬럼들의 데이터 추출:
    Survived  Pclass
0         0       3
1         1       1
2         1       3


KeyError: 0

In [60]:
titanic_df[0:2] # -> 슬라이싱은 가능. 0번부터 2번 전까지 행 추출 (0, 1번 행)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr....",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mr...",female,38.0,1,0,PC 17599,71.2833,C85,C


In [61]:
titanic_df[ titanic_df['Pclass'] == 3].head(3) # -> 불린 인덱싱. Pclass가 3인 행들만 필터링하여 추출

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr....",male,22.0,1,0,A/5 21171,7.250,NaN,S
2,3,1,3,"Heikkinen, ...",female,26.0,0,0,STON/O2. 31...,7.925,NaN,S
4,5,0,3,"Allen, Mr. ...",male,35.0,0,0,373450,8.050,NaN,S


In [62]:
data = {'Name': ['Chulmin', 'Eunkyung','Jinwoong','Soobeom'],
        'Year': [2011, 2016, 2015, 2015],
        'Gender': ['Male', 'Female', 'Male', 'Male']
       } # -> 딕셔너리 데이터 생성
data_df = pd.DataFrame(data, index=['one','two','three','four']) # -> DataFrame 생성. 인덱스를 문자열로 지정
data_df # -> DataFrame 출력

,Name,Year,Gender
one,Chulmin,2011,Male
two,Eunkyung,2016,Female
three,Jinwoong,2015,Male
four,Soobeom,2015,Male


In [63]:
data_df.iloc[0, 0] # -> iloc는 위치 기반 인덱싱. 0행 0열의 값 추출 ('Chulmin')

'Chulmin'

In [64]:
# 아래 코드는 오류를 발생시킵니다.
data_df.iloc[0, 'Name'] # -> iloc는 위치 기반 인덱싱이므로 컬럼명을 쓸 수 없음! 에러 발생

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [65]:
# 아래 코드는 오류를 발생합니다.
data_df.iloc['one', 0] # -> iloc는 위치 기반 인덱싱이므로 인덱스 이름을 쓸 수 없음! 에러 발생

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [66]:
print("\n 맨 마지막 칼럼 데이터 [:, -1] \n", data_df.iloc[:, -1]) # -> 모든 행의 마지막 컬럼 (-1) 추출
print("\n 맨 마지막 칼럼을 제외한 모든 데이터 [:, :-1] \n", data_df.iloc[: , :-1]) # -> 모든 행의 마지막 컬럼을 제외한 모든 컬럼 추출


 맨 마지막 칼럼 데이터 [:, -1] 
 one        Male
two      Female
three      Male
four       Male
Name: Gender, dtype: object

 맨 마지막 칼럼을 제외한 모든 데이터 [:, :-1] 
            Name  Year
one     Chulmin  2011
two    Eunkyung  2016
three  Jinwoong  2015
four    Soobeom  2015


In [67]:
data_df.loc['one', 'Name'] # -> loc는 이름 기반 인덱싱. 'one' 인덱스의 'Name' 컬럼 값 추출 ('Chulmin')

'Chulmin'

In [68]:
# 아래 코드는 오류를 발생합니다. 
data_df_reset.loc[0, 'Name'] # -> data_df_reset이 정의되지 않았으므로 NameError 발생!

NameError: name 'data_df_reset' is not defined

In [69]:
print('위치기반 iloc slicing\n', data_df.iloc[0:1, 0],'\n') # -> iloc 슬라이싱: 0행, 0열 추출
print('명칭기반 loc slicing\n', data_df.loc['one':'two', 'Name']) # -> loc 슬라이싱: 'one'부터 'two'까지, 'Name' 컬럼 추출. loc는 끝 포함!

위치기반 iloc slicing
 one    Chulmin
Name: Name, dtype: object 

명칭기반 loc slicing
 one     Chulmin
two    Eunkyung
Name: Name, dtype: object


In [73]:
titanic_df = pd.read_csv('train.csv')
titanic_boolean = titanic_df[titanic_df['Age'] > 60]
print(type(titanic_boolean))
titanic_boolean

<class 'pandas.core.frame.DataFrame'>


,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr...",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. ...",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,Goldschmidt...,male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr...",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,Van der hoe...,male,61.0,0,0,111240,33.5000,B19,S
252,253,0,1,"Stead, Mr. ...",male,62.0,0,0,113514,26.5500,C87,S
275,276,1,1,"Andrews, Mi...",female,63.0,1,0,13502,77.9583,D7,S
280,281,0,3,"Duane, Mr. ...",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr...",male,61.0,0,0,345364,6.2375,NaN,S
438,439,0,1,"Fortune, Mr...",male,64.0,1,4,19950,263.0000,C23 C25 C27,S


In [74]:
titanic_df[titanic_df['Age'] > 60][['Name','Age']].head(3) # -> 60세 초과인 사람들의 이름과 나이만 추출하여 처음 3개 출력

,Name,Age
33,"Wheadon, Mr...",66.0
54,"Ostby, Mr. ...",65.0
96,Goldschmidt...,71.0


In [75]:
titanic_df.loc[titanic_df['Age'] > 60, ['Name','Age']].head(3) # -> loc를 사용한 불린 인덱싱. 위와 동일하지만 더 효율적

,Name,Age
33,"Wheadon, Mr...",66.0
54,"Ostby, Mr. ...",65.0
96,Goldschmidt...,71.0


In [76]:
titanic_df[ (titanic_df['Age'] > 60) & (titanic_df['Pclass']==1) & (titanic_df['Sex']=='female')] # -> 3개 조건을 AND(그리고)로 결합. 60세 초과 + 1등석 + 여성

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
275,276,1,1,"Andrews, Mi...",female,63.0,1,0,13502,77.9583,D7,S
829,830,1,1,"Stone, Mrs....",female,62.0,0,0,113572,80.0000,B28,NaN


In [77]:
cond1 = titanic_df['Age'] > 60 # -> 조건 1: 나이가 60보다 큰가?
cond2 = titanic_df['Pclass']==1 # -> 조건 2: Pclass가 1인가?
cond3 = titanic_df['Sex']=='female' # -> 조건 3: 성별이 여성인가?
titanic_df[ cond1 & cond2 & cond3] # -> 세 조건을 모두 만족하는 행들만 필터링. 위와 동일한 결과

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
275,276,1,1,"Andrews, Mi...",female,63.0,1,0,13502,77.9583,D7,S
829,830,1,1,"Stone, Mrs....",female,62.0,0,0,113572,80.0000,B28,NaN


## 정렬, Aggregation함수, GroupBy 적용


In [78]:
titanic_sorted = titanic_df.sort_values(by=['Name']) # -> 'Name' 컬럼을 기준으로 오름차순 정렬
titanic_sorted.head(3) # -> 정렬된 결과의 처음 3개 행 출력

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
845,846,0,3,"Abbing, Mr....",male,42.0,0,0,C.A. 5547,7.55,NaN,S
746,747,0,3,"Abbott, Mr....",male,16.0,1,1,C.A. 2673,20.25,NaN,S
279,280,1,3,"Abbott, Mrs...",female,35.0,1,1,C.A. 2673,20.25,NaN,S


In [79]:
titanic_sorted = titanic_df.sort_values(by=['Pclass', 'Name'], ascending=False) # -> 'Pclass'로 먼저 정렬 후 'Name'으로 정렬. ascending=False로 내림차순
titanic_sorted.head(3) # -> 정렬된 결과의 처음 3개 행 출력

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
868,869,0,3,van Melkebe...,male,NaN,0,0,345777,9.5,NaN,S
153,154,0,3,van Billiar...,male,40.5,0,2,A/5. 851,14.5,NaN,S
282,283,0,3,de Pelsmaek...,male,16.0,0,0,345778,9.5,NaN,S


* Aggregation 함수 적용

In [80]:
titanic_df.count() # -> 각 컬럼별로 Non-Null(결측값이 아닌) 데이터의 개수 세기

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [81]:
titanic_df[['Age', 'Fare']].mean() # -> 'Age'와 'Fare' 컬럼의 평균값 계산

Age     29.699118
Fare    32.204208
dtype: float64

* groupby() 이용하기

In [82]:
titanic_groupby = titanic_df.groupby(by='Pclass') # -> 'Pclass'로 그룹화. 아직 집계 함수를 적용하지 않은 GroupBy 객체
print(type(titanic_groupby)) # -> pandas.core.groupby.generic.DataFrameGroupBy 타입

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


In [83]:
titanic_groupby = titanic_df.groupby('Pclass').count() # -> 'Pclass'로 그룹화한 후 각 그룹별로 Non-Null 데이터 개수 세기
titanic_groupby # -> 그룹별 카운트 결과 출력

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,,,,,,,,,,,
1,216,216,216,216,186,216,216,216,216,176,214
2,184,184,184,184,173,184,184,184,184,16,184
3,491,491,491,491,355,491,491,491,491,12,491


In [84]:
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId', 'Survived']].count() # -> 'Pclass'로 그룹화 후 특정 컬럼만 선택하여 카운트
titanic_groupby # -> 그룹별 특정 컬럼의 카운트 결과

,PassengerId,Survived
Pclass,,
1,216,216
2,184,184
3,491,491


In [85]:
titanic_df.groupby('Pclass')['Age'].agg([max, min]) # -> 'Pclass'로 그룹화 후 'Age'의 최댓값과 최솟값을 동시에 계산

C:\Users\남궁하람\AppData\Local\Temp\ipykernel_33136\721218593.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max, min]) # -> 'Pclass'로 그룹화 후 'Age'의 최댓값과 최솟값을 동시에 계산
C:\Users\남궁하람\AppData\Local\Temp\ipykernel_33136\721218593.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max, min]) # -> 'Pclass'로 그룹화 후 'Age'의 최댓값과 최솟값을 동시에 계산


,max,min
Pclass,,
1,80.0,0.92
2,70.0,0.67
3,74.0,0.42


In [86]:
agg_format={'Age':'max', 'SibSp':'sum', 'Fare':'mean'} # -> 딕셔너리 형태로 컬럼별 집계 함수 지정
titanic_df.groupby('Pclass').agg(agg_format) # -> 'Pclass'로 그룹화 후 각 컬럼에 지정된 집계 함수 적용

,Age,SibSp,Fare
Pclass,,,
1,80.0,90,84.154687
2,70.0,74,20.662183
3,74.0,302,13.675550


## 결손 데이터 처리하기

In [87]:
titanic_df.isna().head(3) # -> isna() 메서드로 결측값(NaN) 여부 확인. True/False로 반환됨

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False


In [88]:
titanic_df.isna( ).sum( ) # -> 각 컬럼별로 결측값의 총 개수 집계

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

* fillna( ) 로 Missing 데이터 대체하기

In [89]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000') # -> 'Cabin' 컬럼의 결측값을 'C000'으로 대체
titanic_df.head(3) # -> 결과 확인

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr....",male,22.0,1,0,A/5 21171,7.2500,C000,S
1,2,1,1,"Cumings, Mr...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, ...",female,26.0,0,0,STON/O2. 31...,7.9250,C000,S


In [90]:
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean()) # -> 'Age' 컬럼의 결측값을 평균값으로 대체
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S') # -> 'Embarked' 컬럼의 결측값을 'S'로 대체
titanic_df.isna().sum() # -> 대체 후 결측값 개수 다시 확인. Age와 Embarked의 결측값이 0이 됨

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

## apply lambda 식으로 데이터 가공

In [91]:
def get_square(a): # -> 제곱을 계산하는 일반 함수 정의
    return a**2

print('3의 제곱은:',get_square(3)) # -> 함수 호출하여 3의 제곱 계산

3의 제곱은: 9


In [92]:
lambda_square = lambda x : x ** 2 # -> lambda 식으로 동일한 제곱 함수 정의. 한 줄로 간결하게 표현
print('3의 제곱은:',lambda_square(3)) # -> lambda 함수 호출하여 3의 제곱 계산

3의 제곱은: 9


In [93]:
a=[1,2,3] # -> 리스트 생성
squares = map(lambda x : x**2, a) # -> map() 함수로 리스트의 각 원소에 lambda 함수 적용
list(squares) # -> map 객체를 리스트로 변환하여 결과 출력 [1, 4, 9]

[1, 4, 9]

In [94]:
titanic_df['Name_len']= titanic_df['Name'].apply(lambda x : len(x)) # -> 'Name' 컬럼의 각 이름 길이를 계산하여 새 컬럼 'Name_len' 생성
titanic_df[['Name','Name_len']].head(3) # -> 이름과 이름 길이 컬럼만 추출하여 처음 3개 출력

,Name,Name_len
0,"Braund, Mr....",23
1,"Cumings, Mr...",51
2,"Heikkinen, ...",22


In [95]:
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x <=15 else 'Adult' ) # -> 15세 이하면 'Child', 아니면 'Adult'로 분류
titanic_df[['Age','Child_Adult']].head(8) # -> 나이와 분류 결과 컬럼만 추출하여 처음 8개 출력

,Age,Child_Adult
0,22.000000,Adult
1,38.000000,Adult
2,26.000000,Adult
3,35.000000,Adult
4,35.000000,Adult
5,29.699118,Adult
6,54.000000,Adult
7,2.000000,Child


In [96]:
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : 'Child' if x<=15 else ('Adult' if x <= 60 else 
                                                                                  'Elderly')) # -> 3단계 분류: 15세 이하 'Child', 60세 이하 'Adult', 60세 초과 'Elderly'
titanic_df['Age_cat'].value_counts() # -> 각 카테고리별 인원수 집계

Age_cat
Adult      786
Child       83
Elderly     22
Name: count, dtype: int64

In [97]:
# 나이에 따라 세분화된 분류를 수행하는 함수 생성. 
def get_category(age): # -> 나이를 받아서 7단계로 세분화하는 함수
    cat = ''
    if age <= 5: cat = 'Baby' # -> 5세 이하: Baby
    elif age <= 12: cat = 'Child' # -> 12세 이하: Child
    elif age <= 18: cat = 'Teenager' # -> 18세 이하: Teenager
    elif age <= 25: cat = 'Student' # -> 25세 이하: Student
    elif age <= 35: cat = 'Young Adult' # -> 35세 이하: Young Adult
    elif age <= 60: cat = 'Adult' # -> 60세 이하: Adult
    else : cat = 'Elderly' # -> 60세 초과: Elderly
    
    return cat

# lambda 식에 위에서 생성한 get_category( ) 함수를 반환값으로 지정. 
# get_category(X)는 입력값으로 'Age' 컬럼 값을 받아서 해당하는 cat 반환
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : get_category(x)) # -> 각 나이를 7단계 카테고리로 분류
titanic_df[['Age','Age_cat']].head() # -> 나이와 카테고리 컬럼만 추출하여 처음 5개 출력
    

,Age,Age_cat
0,22.0,Student
1,38.0,Adult
2,26.0,Young Adult
3,35.0,Young Adult
4,35.0,Young Adult
