### **Numpy(Numerical Python)**

: 선형대수 기반 프로그램을 쉽게 만들 수 있도록 지원하는 파이썬 라이브러리

- 루프를 사용하지 않고 대량 데이터의 배열 연산 가능 → 빠른 연산 속도
- 저수준 언어 기반의 호환 API 제공 → 수행 성능 보장

<aside>

**용어 정리**

- 속성[객체.속성]: 배열의 구조 정보를 저장한 값
- 함수[함수(  )]: 객체에 속하지 않은 독립적인 기능
- 메서드[객체.기능(  )]: 객체에 속한 함수

cf. 같은 연산이 함수와 메서드의 두 방식으로 제공되는 경우가 많다.

</aside>

### **Numpy ndarray 개요**

**ndarray** : 넘파이의 기반 데이터 타입으로 다차원 배열 생성 및 연산 수행

<aside>

**데이터 타입**

- ndarray 내 데이터 타입은 **같은 데이터 타입만** 가능
- 다른 데이터 유형이 섞여 있는 경우, **크기가 더 큰 데이터 타입**으로 형 변환
</aside>



**관련 넘파이 API**

- np.array(  ) : 다양한 인자를 입력받아 ndarray로 변환하는 함수
- a.shape : ndarray의 크기(행과 열)을 보여주는 속성
- a.ndim : array의 차원을 보여주는 속성
- a.dtype : 데이터 타입을 보여주는 속성
- a.astype(  ) : 데이터 값 타입을 변경하는 메서드

In [1]:
import numpy as np

In [3]:
# 1차원
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

# 2차원
array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

# 2차원
array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [5]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,array2.ndim,array3.ndim))


array1: 1차원, array2: 2차원, array3: 2차원


In [8]:
# 숫자형 데이터 타입
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [9]:
# 데이터 타입이 다른 경우
# Case 1: string이 섞여 있을 경우 -> int가 string으로 변환
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

# Case 2: float이 섞여 있을 경우 -> int가 float으로 변환
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [11]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### **ndarray를 편리하게 생성하기 - arange, zeros, ones**

⬇️대규모의 데이터를 일괄적으로 초기화해야 할 경우 사용⬇️

**관련 넘파이 API**

- np.arange( start, stop ) : stop-1 까지의 연속된 숫자 값으로 1차원 ndarray를 만드는 함수; start 값 선택 옵션(default = 0)
- np.zeros( shape, dtype=’  ‘ ) : 모든 값을 0으로 채운 해당 shape을 가진 ndarray를 만드는 함수 ; dtype 값 선택 옵션
- np.ones( shape, dtype=’  ‘ ) : 모든 값을 1으로 채운 해당 shape을 가진 ndarray를 만드는 함수 ; dtype 값 선택 옵션(default = float64)

In [14]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [13]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### **reshape**

**특징**

- 지정된 사이즈로 **변경이 불가능하면 오류** 발생
- **‘-1’ 인자** : 원래 ndarray와 호환되는 새로운 shape으로 변환
    - why? 데이터 크기가 바뀌어도 자동으로 변경 가능
    - **reshape( -1, -1 ) 사용 불가** → 두 차원을 동시에 계산 X
    - reshape( -1, 1 ) 사용 → ndarray 결합 시 형태 통일에 유용

**관련 넘파이 API**

- a.reshape( row, column ) : ndarray를 특정 차원 및 크기로 변환하는 메서드
- a.tolist(  ) : 배열을 리스트 자료형으로 변환하는 메서드
    
    cf. 리스트는 ‘,’로 구분하며 결과가 한 줄로 작성됨

In [15]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [17]:
# 전체 데이터 개수(10)와 배열 크기가 일치하지 않아 오류 발생
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [19]:
array1 = np.arange(10)
print(array1)

# -1 인자로 자동 계산
array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [21]:
# 전체 데이터 개수(10)와 배열 크기가 일치하지 않아 오류 발생
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [22]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### **indexing**

**indexing** : ndarray 내의 일부 데이터 세트나 특정 데이터만을 선택

- **특정한 데이터만 추출**
    - 1차원 : a[ index ]
    - 2차원 이상 : a[ axis 0, axis 1 … ]
    - ‘-’ 기호 사용을 통해 맨 뒤에서 데이터 추출 가능(ex. a[ -1 ] = 맨 뒤 데이터)
    
    cf. **axis**란 **어느 방향으로 축소하느냐**를 의미 → 기본적으로 axis 0은 행 방향, axis 1은 열 방향

In [23]:
# 1에서 부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [24]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [25]:
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [26]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


- **슬라이싱(Slicing)**
    
    : ‘:’ 기호를 이용해 연속한 데이터를 추출하는 방식으로 stop-1까지 반환 ; start와 stop은 선택 옵션
    
    - 1차원 : a[ start:stop ]
    - 2차원 이상 : a[ start:stop, start:stop … ] → 뒤에 오는 index를 없애면 차원-1 배열 반환

In [27]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [28]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [29]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [30]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


- **팬시 인덱싱(Fancy Indexing)**
    
    : 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 배열 반환
    
    - 2차원 : a[ [ axis 0, axis 1 ], index(slicing) ]

In [31]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


- **불린 인덱싱(Boolean Indexing)**
    
    : 조건 필터링과 검색을 동시에 할 수 있는 인덱싱
    
    - a[ 조건문 ]
    - 동작 과정 : 조건문 → False / True 로 판단 → True 값의 **인덱스 값**만 저장 → 저장된 인덱스 데이터 세트로 배열 조회
    
    cf. a[[ index ]] : 여러 인덱스를 선택 / a[ index ] : 다차원 인덱싱

In [32]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [33]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [34]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [35]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### **행렬의 정렬 – sort( )와 argsort( )**

**특징**

- 넘파이는 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 가져야함
- 기본 오름차순 정렬 ; [ : : -1 ]을 끝에 붙여 **내림차순** 정렬 수행
- 2차원 이상 : sort( a, axis=n ) → axis 방향 정렬 수행

**관련 넘파이 API**

- np.sort(  ) : 원 행렬은 유지한 채 정렬된 행렬을 반환
- a.sort(  ) : 원 행렬 자체를 정렬된 행렬로 변환하며 반환 값은 None
- np.argsort(  ) : 정렬된 행렬의 인덱스를 반환

In [36]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)
# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)
# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)


원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [37]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


In [38]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


* 정렬 행렬의 인덱스 반환

In [39]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [40]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [42]:
import numpy as np

# 시험 성적을 데이터로 표현하기 위해 학생의 이름과 성적이 각각 배열로 존재
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

# 시험 성적순으로 학생 이름을 출력할 경우 -> 인덱스 반환
sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)

# 반환된 인덱스를 팬시 인덱스로 활용
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### **선형대수 연산 – 행렬 내적과 전치 행렬 구하기**

- **행렬 내적** : 행렬의 곱으로 왼쪽 행렬의 열과 오른쪽 행렬의 행 개수가 동일해야 함

<img src="행렬내적.png" width="400">

- **전치 행렬** : 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬

<img src="전치행렬.png" width="400">

**관련 넘파이 API**

- np.dot( a, b ) : 행렬 내적 계산
- np.transpose( a ) : 전치 행렬 계산

In [46]:
# 행렬 내적
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [47]:
# 전치 행렬
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
