## 넘파이 nadarray 개요

In [12]:


import numpy as np
array1 = np.array([1,2,3])

In [5]:
print('array1 tpye:', type(array1))
print('array1 array 형태:', array1.shape)

array1 tpye: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [10]:
array2 = np.array([[1,2,3],[2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)
array3= np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (2, 3)


In [11]:
print('array1: {0}차원, array2: {1}차원, array3:{2}차원'.format(array1.ndim,array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:2차원


## ndarray의 데이터 타입

In [13]:
list1 = [1,2,3]  # 리스트 자료형 int32형
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [16]:
list2 = [1,2, 'test']   # test 로 인해 문자열로 변환. 다른 타입이 있을경우 더 큰데이터 타입으로 변환
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]   # 3.0 으로 인해 float64로 변환
array3 = np.array(list3)
print(array3,array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [19]:
array_int = np.array([1,2,3]) # astype() 메서드에서 원하는 타입을 지정할 수 있다.
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


## ndarray를 편리하게 생성하기 - arange, zeros, ones

In [20]:
sequence_array = np.arange(10)  #arange 는 range 와 유사
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [22]:
zero_array = np.zeros((3,2), dtype='int32')  # shape 을 입력하면 모든 값을 1로 채운 해당 shape을 가진 ndarray를 반환합니다.
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.zeros((3,2), dtype='int32')
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


## ndarray의 차원과 크기를 변경하는 reshape()

In [24]:
array1 = np.arange(10)  # 특정 차원 및 크기로 변환한다.
print('array1:\n', array1)

array2 = array1.reshape(2,5) # 2로우 5칼럼으로 변환한다.
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [26]:
## array1.reshape(4,3) 불가

In [28]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [30]:
## array1.np.arange(10)
## array4 = array1.reshape(-1,4)

In [31]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5= array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


## 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱

### 단일 값 추출

In [35]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)
# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value=array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [36]:
print('맨 뒤의 값:', array1[-1], ' 맨뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9  맨뒤에서 두 번째 값: 8


In [38]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [40]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


### 슬라이싱

In [42]:
array1 = np.arange(start=1, stop=10) #:기호를 이용해 연속한 데이터를 슬라이싱해 추출한다.
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [43]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]  # 인덱스 0 간주
print(array4)

array5= array1[3:] # 마지막 인덱스로 간주
print(array5)

array6 = array1[:] # 처음부터 끝까지로 간주
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [44]:
array1d = np.arange(start=1, stop=10) # 2차원 ndarray 도 마찬가지 , 로 로우와 칼럼 인덱스 구분
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n' , array2d[1:3, :])
print('array2d[:,:] \n', array2d[:,:])
print('array2d[:2, 1:] \n' , array2d[:2,1:])
print('array2d[:2, 0] \n', array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:,:] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [46]:
print(array2d[0]) # 2차원 인덱스에서 뒤에오는 인덱스를 없애면 1차원을 반환
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


### 팬시 인덱싱
#### 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [48]:
array1d= np.arange(start=1, stop=10) 
array2d= array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] =>', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] =>', array4.tolist())

array5= array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1], 0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


### 불린 인덱싱
#### 자주 사용됨. 조건 필터링과 검색을 둥시에. []내에 조건문을 그대로 기재하면된다.

In [50]:
array1d = np.arange(start=1, stop=10)
# []안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [52]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [53]:
boolean_indexes = np.array([False, False, False,False, False,True,True,True,True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :',array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [54]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


#### step 1: ndarray 의 필터링 조건을 [] 안에 기재
#### step 2: false 값은 무시하고 true값에 해당하는 인덱스 값만 저장
#### step 3: 저장된 인덱스 데이터 세트로 ndarray 조회

## 행렬의 정렬 - sort()와 argsort()
### 행렬 정렬

In [56]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)
# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort()호출 후 반환된 정렬 행렬:', sort_array1)

원본 행렬: [3 1 9 5]
np.sort()호출 후 반환된 정렬 행렬: [1 3 5 9]
