넘파이 ndarray 개요

In [1]:
import numpy as np #넘파이 모듈 불러오기

In [2]:
array1=np.array([1,2,3]) #array(): 인자를 입력받아 넘파이의 데이터 타입인 ndarray로 변환 /1차원
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

array2=np.array([[1,2,3],
                 [2,3,4]]) #2차원
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3=np.array([[1,2,3]]) #2차원
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [4]:
print('array1: {0}차원,array2:{1}차원,array3:{2}차원'.format(array1.ndim,array2.ndim,array3.ndim))
#ndarray.ndim 을 이용해 각 array의 차원 확인

array1: 1차원,array2:2차원,array3:2차원


ndarray의 데이터 타입

In [5]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1) #리스트와 달리 같은 데이터 타입만 나열 가능
print(type(array1))
print(array1,array1.dtype) #데이터 타입은 dtype이용해서 확인

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [6]:
list2=[1,2,'test'] #다른 데이터 유형이 섞여있는 경우 더 큰 데이터 타입으로 형변환
array2=np.array(list2)
print(array2,array2.dtype)# 모두 문자열(유나코드) 값으로 변환

list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype) #모두 float64형으로 변환

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [8]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64') #astype()이용해서 데이터값 타입 변경
print(array_float,array_float.dtype)

array_int1=array_float.astype('int32') #floate을 int로 변경
print(array_int1,array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1]) 
array_int2=array_float1.astype('int32') #float을 int로 변경
print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


ndarray를 편리하게 생성하기-arange,zeros,ones

In [10]:
sequence_array=np.arange(10) #arange():0부터 함수인자-1까지의 값을 순차적으로 ndarray 데이터값으로 변경
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [11]:
zero_array = np.zeros((3,2), dtype='int32') #zeros(): 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape을 가진 ndarray 반환
print(zero_array)
print(zero_array.dtype, zero_array.shape)
one_array = np.ones((3,2)) #ones():모든 값을 1로 채운 ndarray 반환 / dtype 안 정해주면 float64형으로 채움
print(one_array)
print(one_array.dtype, one_array.shape)


[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


ndarray의 차원과 크기를 변경하는 reshape()

In [12]:
array1=np.arange(10) #reshape은 ndarray를 특정 차원 및 크기로 변환
print('array1:\n', array1)

array2= array1.reshape(2,5)
print('array2:\n', array2)

array3= array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
array1.reshape(4,3) #(10,)데이터를 2차원으로 변경 불가-오류발생

ValueError: cannot reshape array of size 10 into shape (4,3)

In [14]:
array1= np.arange(10)
print(array1)
array2= array1.reshape(-1,5) #-1을 사용해 호환될 수 있는 2차원의 ndarray로 변환
print('array2 shape:',array2.shape)
array3= array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [16]:
array1=np.arange(10)
array4=array1.reshape(-1,4) #10개의 1차원 데이터를 4개의 행인 열로 변환 불가능하기 때문에 오류 발생

ValueError: cannot reshape array of size 10 into shape (4)

In [18]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist()) #tolist()를 통해 리스트 자료형으로 변환

array5=array3d.reshape(-1,1) #3차원을 2차원으로 변환
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

array6=array1.reshape(-1,1) #1차원을 2차원으로 변환
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)

-단일 값 추출

In [19]:
array1=np.arange(start=1, stop=10) #1부터 9
print('array1:',array1)
value=array1[2] # 1개의 데이터 값 선택하려면 ndarray객체에 해당하는 위치의 인덱스 값을 []안에 입력
print('value:',value)
print(type(value))


array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [20]:
print('맨 뒤의 값:', array1[-1],'맨 뒤에서 두 번째 값:',array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [21]:
array1[0]=9 #단일 인덱스로 데이터 값 간단히 수정 가능
array1[8]=0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [22]:
array1d=np.arange(start=1,stop=10) 
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0]) #다차원에서 단일 값 추출하는 방법
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


-슬라이싱

In [23]:
array1=np.arange(start=1,stop=10)
array3=array1[0:3] #':'기호 이용하여 슬라이싱해서 추출할 수 있음,슬라이싱한 데이터는 ndarray 타입
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [25]:
array1=np.arange(start=1,stop=10)
array4=array1[:3] #':'기호 앞 시작 인덱스 생략 시 0인덱스로 간주
print(array4)

array5=array1[3:] #':'기호 뒤 종료 인덱스 생략 시 마지막 인덱스로 간주
print(array5)

array6=array1[:] #':'기호 앞/뒤 인덱스 생략 시 맨 처음/마지막 인덱스로 간주
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [28]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2,0:2]\n', array2d[0:2,0:2]) #2차원에서 슬라이싱 하는법
print('array2d[1:3,0:3]\n', array2d[1:3,0:3])
print('array2d[1:3,:]\n', array2d[1:,:])
print('array2d[:,:]\n', array2d[:,:])
print('array2d[:2,1:]\n', array2d[:2,1:])
print('array2d[:2,0]\n', array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]


In [29]:
print(array2d[0])
print(array2d[1])
print('array2d[0]shape:',array2d[0].shape,'array2d[1]shape:',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0]shape: (3,) array2d[1]shape: (3,)


-팬시 인덱싱 :리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [30]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2]=>',array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>',array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]]=>',array5.tolist())

array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


-불린 인덱싱 :조건 필터링과 인덱싱 

In [31]:
array1d=np.arange(start=1,stop=10) 
array3=array1d[array1d>5] # 조건 적용해서 인덱싱 가능
print('array1d>5 불린 인덱싱 결과 값:',array3)

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


In [32]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [35]:
boolen_indexes=np.array([False, False, False, False, False,  True,  True,  True,  True])
array3=array1d[boolen_indexes]
print('불린 인덱스로 필터링 결과 :',array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [36]:
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과:',array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


행렬의 정렬-sort()와 argsort()

-행렬 정렬

In [38]:
org_array = np.array([3,1,9,5]) 
print('원본 배열:', org_array) 
sort_array1 = np.sort(org_array) #np.sort()로 정렬:원행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬 반환 
print('np.sort()호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort()호출 후 원본 행렬:', org_array)

sort_array2=org_array.sort() #ndarray.sort()로 정렬:원행렬 자체를 정렬한 형태로 반환하며 반환값 None 
print('org_array.sort()호출 후 반환된 정렬 행렬:', sort_array2) 
print('org_array.sort()호출 후 원본 행렬:', org_array)

#둘 다 기본적으로 오름차순 정렬

원본 배열: [3 1 9 5]
np.sort()호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort()호출 후 원본 행렬: [3 1 9 5]
org_array.sort()호출 후 반환된 정렬 행렬: None
org_array.sort()호출 후 원본 행렬: [1 3 5 9]


In [39]:
sort_array1_desc=np.sort(org_array)[::-1] #내림차순 정렬하는 법:[::-1] 적용
print('내림차순으로 정렬:',sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [40]:
array2d=np.array([[8,12],[7,1]])
#2차원인 경우 axis 축 값 설정을 통해 로우 방향, 칼럼 방향으로 정렬

sort_array2d_axis0=np.sort(array2d,axis=0)
print('로우 방향으로 정렬:\n',sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d,axis=1)
print('칼럼 방향으로 정렬:\n',sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


-정렬된 행렬의 인덱스를 반환하기

In [44]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array) 
#np.argsort()이용하여 원본 행렬 인덱스를 ndarray형으로 반환
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [43]:
org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:',sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [45]:
import numpy as np

name_array=np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:',sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:',name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


선형대수 연산 - 행렬 내적과 전치 행렬 구하기

-행렬 내적(행렬 곱)

In [46]:
A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([[7,8],
           [9,10],
           [11,12]])

dot_product=np.dot(A,B) #np.dot 이용
print('행렬 내적 결과:\n',dot_product)


행렬 내적 결과:
 [[ 58  64]
 [139 154]]


-전치 행렬

In [47]:
A=np.array([[1,2],
           [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치행렬:\n',transpose_mat)

A의 전치행렬:
 [[1 3]
 [2 4]]
