In [7]:
import numpy as np

In [11]:
array1 = np.array([1,2,3])
print('array1 type', type(array1))
print('array1 array 형태', array1.shape) #1차원 1행3열 3개 데이터

array2 = np.array([[1,2,3],[2,3,4]])
print('array2 type', type(array2))
print('array2 array 형태', array2.shape) #2차원 2행3열, 6개데이터

array3 = np.array([[1,2,3]])
print('array3 type', type(array3))
print('array3 array 형태', array3.shape) # 2차원 데이터

array1 type <class 'numpy.ndarray'>
array1 array 형태 (3,)
array2 type <class 'numpy.ndarray'>
array2 array 형태 (2, 3)
array3 type <class 'numpy.ndarray'>
array3 array 형태 (1, 3)


In [13]:
# 각 array의 차원
print(array1.ndim, array2.ndim, array3.ndim)

1 2 2


In [17]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [23]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [25]:
# ndarray 내 타입 변경
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [31]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [33]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [45]:
array1 = np.arange(10)
print('array1:\n',array1)

array2 = array1.reshape(2,5)
print(array2)

array3 = array1.reshape(5,2)
print(array3)

array4 = array1.reshape(-1,5) # -1을 사용하면 원래와 호환되는 새로운 shape으로 변환
print(array4.shape)

array5 = array1.reshape(-1,1)
print(array5.tolist()) # (-1.1)은 원본이 어떤 형태라도 2차원, 여러개 로우를 가져도 반드시 한개의 컬럼을 가짐

array1:
 [0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(2, 5)
[[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]]


In [51]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print(array3d.tolist()) #리스트 자료형으로 변환해 출력

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print(array5.tolist(), array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print(array1)
print(array6.tolist(), array6.shape)

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
[[0], [1], [2], [3], [4], [5], [6], [7]] (8, 1)
[0 1 2 3 4 5 6 7]
[[0], [1], [2], [3], [4], [5], [6], [7]] (8, 1)


In [53]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1,stop=10)
print(array1)

# index는 0부터 시작하므로 array1[2]는 3번째값 의미
value = array1[2]
print(type(value), value)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.int32'> 3


In [57]:
# 인덱스 -1은 맨 뒤의 데이터값을 의미
print(array1[-1])
print(array1[-2])

9
8


In [59]:
array1[8] = 0
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 0])

In [65]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print(array2d[0,0])
print(array2d[0,1])
print(array2d[1,0])
print(array2d[2,2])
# axis 0은 row 방향, axis 1은 칼럼방향의 축을 의미

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
4
9


In [67]:
array1 = np.arange(start=1,stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [71]:
# slicing
# : 앞에 시작 인덱스를 생략하면 처음 인덱스인 0, 종료인덱스 생략하면 맨 마지막 인덱스로 간주
array1 = np.arange(start=1,stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [73]:
# 2차원 슬라이싱
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print(array2d[0:2,0:2])
print(array2d[1:3,0:3])
print(array2d[1:3,0:3])
print(array2d[:,:])
print(array2d[:2,1:])
print(array2d[:2,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[1 4]


In [75]:
print(array2d[0])
print(array2d[1]) #1차원이 됨

[1 2 3]
[4 5 6]


In [77]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print(array3.tolist())

array4 = array2d[[0,1],0:2]
print(array4.tolist())

array5 = array2d[[0,1]]
print(array5.tolist())

[3, 6]
[[1, 2], [4, 5]]
[[1, 2, 3], [4, 5, 6]]


In [79]:
array1d = np.arange(start=1,stop=10)
# [] 안에 array1d >5 Boolean indexing 을 적용
array3 = array1d[array1d > 5]
print(array3)

[6 7 8 9]


In [81]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [83]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
# false 는 무시하고 true 값에 해당하는 인덱스 값만 저장 [5,6,7,8]
array3 = array1d[boolean_indexes]
print(array3)

[6 7 8 9]


In [87]:
org_array = np.array([3,1,9,5])
print(org_array)
# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print(sort_array1)
print('np.sort() 호출 후 원본행렬', org_array)
# ndarray.sort() 로 정렬
sort_array2 = org_array.sort()
print(sort_array2)
print('org_array.sort() 호출 후 원본행렬', org_array) # 원본 행렬 자체를 정렬한 값으로 변환

[3 1 9 5]
[1 3 5 9]
np.sort() 호출 후 원본행렬 [3 1 9 5]
None
org_array.sort() 호출 후 원본행렬 [1 3 5 9]


In [89]:
# 내림차순 정렬은 [::-1]
sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)

[9 5 3 1]


In [91]:
array2d = np.array([[8,12],[7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼람 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼람 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [95]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print(sort_indices) # 기존 원본 행렬의 원소에 대한 인덱스를 ndarray 형으로 반환

sort_indices_decs = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬시 원본 행렬의 인덱스', sort_indices_decs)

<class 'numpy.ndarray'>
[1 0 3 2]
행렬 내림차순 정렬시 원본 행렬의 인덱스 [2 3 0 1]


In [97]:
import numpy as np

name_array = np.array(['john', 'mike', 'sarah', 'kate', 'samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬시 score_array의 인덱스', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름출력', name_array[sort_indices_asc])

성적 오름차순 정렬시 score_array의 인덱스 [0 2 4 1 3]
성적 오름차순으로 name_array의 이름출력 ['john' 'sarah' 'samuel' 'mike' 'kate']


In [101]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])
dot_product = np.dot(A,B)
print(dot_product)

[[ 58  64]
 [139 154]]


In [103]:
A = np.array([[1,2],[3,4]])
transpose_mat = np.transpose(A)
print(transpose_mat)

[[1 3]
 [2 4]]
