넘파이 ndarray 개요

In [3]:
import numpy as np #numpy 모듈 임포트

In [ ]:
array1 = np.array([1,2,3]) 
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

#np.array를 통해 원하는 객체를 ndarray로 반환해줌
#type을 통해 ndarray의 차원과 크기를 튜플 형태로 나타냄
array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)


array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)


array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [5]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,
array2.ndim, array3.ndim))
#ndim은 배열의 차원의 수를 표시함. 

array1: 1차원, array2: 2차원, array3: 2차원


ndarray의 데이터 타입

In [6]:
#list를 ndarray로 변경가능함. 
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))

#ndarray내의 데이터 타입을 dtype 속성으로 확인할 수 있음
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [7]:
#ndarray 내의 데이터 타입은 같은 데이터타입만 가능하므로, 가장 큰 데이터 타입으로 일괄 변경함
#모두 문자열 값으로 변환됨.
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

#모두 float64로 변경됨.
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [8]:
# ndarray 내 데이터값의 타입 변경은 astype을 통해서도 가능.
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

# float를 int로 변경할 때 소수점 이하는 모두 사라짐
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


ndarray를 편리하게 생성하기

In [9]:
#array를 range로 표현해줌.
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [10]:
#zeros는 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

#ones는 모든 값을 1로 채워서 ndarray를 반환
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


reshape()

In [11]:
#reshap을 이용하여 ndarray를 특정 차원 및 크기로 변환가능
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)
 
array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [12]:
array1.reshape(4,3)
#reshape은 지정된 사이즈로 변경이 불가능하면 오류를 발생시킴

ValueError: cannot reshape array of size 10 into shape (4,3)

In [ ]:
array1 = np.arange(10)
print(array1)

# 고정된 5개의 칼럼에 맞는 로우를 자동으로 새롭게 생성하여 변환
array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

# 고정된 5개의 로우에 맞는 칼럼을 자동으로 새롭게 생성하여 변환
array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [ ]:
# 10개의 1차원 데이터를 4행 3열의 형태로 만들 수 없어서 오류발생
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
#tolist 메서드를 통해 리스트 자료형으로 변환할 수 있음
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


인덱싱(Indexing)

In [ ]:
# 1에서 부터 9까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [ ]:
# 음수를 이용한 인덱싱도 가능
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [ ]:
#수정 또한 가능
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [ ]:
array1d = np.arange(start=1, stop=10)

# 1차원 ndarray를 2차원 3x3 ndarray로 변환
array2d = array1d.reshape(3,3)
print(array2d)

# [row,col]을 이용해 2차원 ndarray에서 데이터를 추출
print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


-슬라이싱

In [ ]:
#':'기호를 이용해 연속한 데이터를 슬라이싱 가능
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array1 = np.arange(start=1, stop=10)

# 3번째까지 선택
array4 = array1[:3]
print(array4)

# 4번째부터 선택
array5 = array1[3:]
print(array5)

# 전체 선택
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

# 0~1행과 0~1열 추출 (2x2 행렬)
print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
# 1~2행과 0~2열(전체 열) 추출
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
# 1~2행과 전체 열 추출
print('array2d[1:3, :] \n', array2d[1:3, :])
# 전체 행과 전체 열 추출
print('array2d[:, :] \n', array2d[:, :])
# 처음부터 1행까지, 그리고 1열부터 마지막 열까지 추출
print('array2d[:2, 1:] \n', array2d[:2, 1:])
# 처음부터 1행까지의 0번째 열만 추출
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [ ]:
print(array2d[0])
print(array2d[1])

# 기존 (3, 3)인 2차원에서 한 축이 고정되어 1차원으로 리턴됨
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


-팬시 인덱싱

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

# row에 리스트 전달
array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())

# row에는 리스트, col에는 슬라이스
array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())

# row에 리스트, col은 전체
array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


-불린 인덱싱

In [ ]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
# boolean indexing을 이용하면 for loop/if else문보다 간단하게 데이터를 추출 가능함
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [ ]:
#False가 있는 인덱스 0~4는 무시하고 True만 반환하게됨
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
#위와 동일한 불린 ndarray를 만들고 array1d[] 내 인덱스로 입력해도 같은 결과가 나옴
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [16]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


행렬의 정렬 – sort( )와 argsort( )

-행렬 정렬

In [ ]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)
# np.sort( )로 정렬
# 원행렬은 유지한채 정렬된 형태의 배열을 반환
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)
# ndarray.sort( )로 정렬
# 원행렬 자체를 정렬한 형태로 반환하며, 반환값은 None임.
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [ ]:
#내림차순 정렬은 '::-1'을 사용
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


In [ ]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])
#axix=0을 통해 로우 방향으로 정렬
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

#axix=1을 통해 칼럼 방향으로 정렬
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


-정렬 행렬의 인덱스 반환

In [ ]:
org_array = np.array([ 3, 1, 9, 5]) 

#argsort는 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환함
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [ ]:
#내림차순 정렬도 같은방식으로('::-1') 원본 행렬의 인덱스를 구할 수 있음
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [ ]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

#실제값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 각각 가져야 할 때, argsort를 활용함
sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


선형대수 연산 – 행렬 내적과 전치 행렬 구하기

-행렬 내적

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

#dot을 통해 행렬끼리의 내적을 구할 수 있음
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


-전치 행렬

In [25]:
A = np.array([[1, 2],
              [3, 4]])

#transpose를 이용하여 특정 행렬의 전치행렬을 구할 수 있음. 전치행렬은 기존행렬의 행과 열을 바꾼 행렬임
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
