### Numpy ndarray 개요

In [1]:
# numpy 라이브러리를 불러오고 보통 np라는 별칭을 사용한다.
import numpy as np

In [2]:
# 리스트를 이용해 1차원 ndarray 생성
array1 = np.array([1,2,3])
# 배열의 자료형과 구조(shape) 확인
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

# 중첩 리스트를 사용하면 2차원 ndarray 생성
array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

# 리스트를 한 번 더 감싸면 행이 1개인 2차원 배열이 된다.
array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
# ndarray 차원 확인
# ndim : 배열의 차원 수를 의미
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,array2.ndim,array3.ndim))


array1: 1차원, array2: 2차원, array3: 2차원


In [4]:
# list → ndarray 변환
list1 = [1,2,3]
# 리스트의 자료형 확인
print(type(list1))
# numpy 배열로 변환
array1 = np.array(list1)
# ndarray 타입 확인
print(type(array1))
# 배열 값과 데이터 타입 확인
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [5]:
# 서로 다른 타입이 섞인 리스트

# 숫자와 문자열이 같이 있는 경우
list2 = [1, 2, 'test']

# ndarray로 변환하면 전체가 문자열 타입으로 변환된다.
array2 = np.array(list2)
print(array2, array2.dtype)

# 정수와 실수가 같이 있는 경우
list3 = [1, 2, 3.0]

# numpy는 더 큰 범위의 타입(float)으로 자동 변환한다.
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [11]:
# astype을 이용한 dtype 변환

# 정수 배열 생성
array_int = np.array([1, 2, 3])
# 정수 → 실수형(float64) 변환
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

# 다시 정수형(int32)으로 변환
array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

# 실수 배열 생성
array_float1 = np.array([1.1, 2.1, 3.1])
# 실수를 정수형으로 변환 (소수점은 버려짐)
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

In [12]:
# arange : 일정한 간격의 숫자 배열 생성
sequence_array = np.arange(10)

print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)



[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [13]:
# zeros : 모든 값이 0인 배열 생성
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

# ones : 모든 값이 1인 배열 생성
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### reshape

In [14]:
# 0부터 9까지 1차원 ndarray 생성
array1 = np.arange(10)
print('array1:\n', array1)

# 1차원 배열을 2행 5열 형태로 변환
array2 = array1.reshape(2,5)
print('array2:\n',array2)

# 1차원 배열을 5행 2열 형태로 변환
array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [15]:
# 원소 개수(10개)와 맞지 않는 shape으로 변환하면 오류 발생
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [16]:
# -1을 사용하면 남은 차원 크기를 numpy가 자동 계산
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [17]:
# 이 경우도 전체 원소 수가 맞지 않아서 reshape 불가능
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [18]:
# 0부터 7까지 1차원 ndarray 생성
array1 = np.arange(8)
# 3차원 배열로 변환
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### indexing

* 단일값 추출

In [19]:
# 1에서 부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0부터 시작하므로 array1[2]는 세 번째 값
value = array1[2]
print('value:',value)
# 추출한 값의 타입 확인
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [20]:
# 음수 인덱스는 뒤에서부터 접근
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [21]:
# 특정 인덱스의 값 변경 가능
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [22]:
# 1부터 9까지의 값을 3x3 2차원 배열로 변환
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

# 2차원 배열은 [행, 열] 형태로 인덱싱
print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


* Slicing

In [23]:
# 1부터 9까지 ndarray 생성
array1 = np.arange(start=1, stop=10)
# 0번 인덱스부터 2번 인덱스까지 추출 (끝 인덱스는 포함 안 됨)
array3 = array1[0:3]
print(array3)
# 슬라이싱 결과도 ndarray 타입
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [24]:
array1 = np.arange(start=1, stop=10)

# 처음부터 2번 인덱스까지 추출
array4 = array1[:3]
print(array4)

# 3번 인덱스부터 끝까지 추출
array5 = array1[3:]
print(array5)

# 처음부터 끝까지 전체 추출
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [25]:
# 1차원 배열을 3x3 2차원 배열로 변환
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

# 0~1행, 0~1열 추출
print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])

# 1~2행, 0~2열 추출
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])

# 1행부터 끝까지 모든 열 추출
print('array2d[1:3, :]\n', array2d[1:3, :])

# 전체 행과 전체 열 출력
print('array2d[:, :]\n', array2d[:, :])

# 2행부터 끝까지, 1열부터 끝까지 추출
print('array2d[2:, 1:]\n', array2d[2:, 1:])

# 2행부터 끝까지의 0열 추출
print('array2d[2:, 0]\n', array2d[2:, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [26]:
# 2차원 배열에서 행 하나를 추출하면 1차원 ndarray가 됨
print(array2d[0])
print(array2d[1])

# 각 행의 shape 확인
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


* fancy indexing

In [27]:
# 1부터 9까지의 값을 가지는 3x3 배열 생성
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

# 0행과 1행에서 각각 2열 값 추출
array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] =>', array3.tolist())

# 0행과 1행에서 0~1열 추출
array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] =>', array4.tolist())

# 0행과 1행 전체 추출
array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


* Boolean indexing

In [28]:
array1d = np.arange(start=1, stop=10)

# 5보다 큰 값만 Boolean indexing으로 추출
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [29]:
# 각 원소가 조건을 만족하는지 True/False로 반환
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [30]:
# True/False 배열을 직접 만들어서 Boolean indexing 적용
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [31]:
# 일반 인덱스 배열을 이용해 원하는 위치의 값만 추출
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬 – sort( )와 argsort( )

* 행렬 정렬

In [32]:
# 정렬 예제용 배열 생성
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)

# np.sort()는 정렬된 새로운 배열을 반환
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

# ndarray.sort()는 원본 배열 자체를 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [33]:
# 오름차순 정렬 결과를 뒤집어서 내림차순으로 표현
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [34]:
# 2차원 배열 정렬
array2d = np.array([[8, 12],
                    [7, 1]])

# axis=0 : 같은 열끼리 비교하여 행 방향으로 정렬
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

# axis=1 : 같은 행 안에서 열 방향으로 정렬
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


* 정렬 행렬의 인덱스 반환

In [35]:
# argsort()는 정렬된 값 자체가 아니라 정렬 전 원본 배열의 인덱스를 반환
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)

print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [36]:
# 내림차순 정렬 인덱스는 오름차순 인덱스를 뒤집어서 사용
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [37]:
import numpy as np

# 이름 배열과 점수 배열 생성
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

# 점수를 오름차순 정렬했을 때의 인덱스 구하기
sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)

# 정렬 인덱스를 이름 배열에 적용하면 점수 순서대로 이름 출력 가능
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 – 행렬 내적과 전치 행렬 구하기

* 행렬 내적

In [38]:
# 2x3 행렬
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# 3x2 행렬
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# np.dot()으로 행렬 내적 수행
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


* 전치 행렬

In [39]:
# 2x2 행렬 생성
A = np.array([[1, 2],
              [3, 4]])

# 행과 열을 서로 바꾼 전치 행렬 생성
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
