## Numpy ndarray 생성 예제

np.array() 함수를 이용하면 파이썬 리스트를 numpy의 ndarray 형태로 변환할 수 있다.  
또한 ndarray 객체의 shape 속성을 이용하면 배열의 차원과 크기를 확인할 수 있다.

In [4]:
import numpy as np

In [3]:
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


### 결과 분석

- **array1**
  - 1차원 배열
  - shape 값: (3,)
  - 원소가 3개인 1차원 배열

- **array2**
  - 2차원 배열
  - shape 값: (2,3)
  - 2행 3열 구조

- **array3**
  - 2차원 배열
  - shape 값: (1,3)
  - 1행 3열 구조

In [5]:
print('array1:{:0}차원, array2:{:1}차원, array3: {:2}차원'.format(array1. ndim, array2.ndim, array3. ndim))

array1:1차원, array2:2차원, array3:  2차원


## ndarray의 차원 확인

numpy 배열의 차원은 `ndim` 속성을 이용하여 확인할 수 있다.  
`ndim`은 배열의 차원의 개수를 반환한다.

예를 들어,
- 1차원 배열 → ndim = 1
- 2차원 배열 → ndim = 2

`format()` 함수를 이용하여 각 배열의 차원을 출력하였다.

In [6]:
list1=[1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1. dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


## Python List를 NumPy ndarray로 변환

파이썬의 리스트(list)는 기본적인 데이터 저장 구조이며 다양한 데이터 타입을 저장할 수 있다.  
하지만 NumPy에서는 수치 연산을 효율적으로 수행하기 위해 **ndarray 객체**를 사용한다.

`np.array()` 함수를 이용하면 파이썬 리스트를 NumPy의 ndarray로 변환할 수 있다.

위 코드에서는 먼저 `type()` 함수를 이용하여 list1의 타입을 확인하였다.  
그 결과 list1은 `<class 'list'>`로 파이썬 리스트임을 알 수 있다.

이후 `np.array()` 함수를 사용하여 리스트를 ndarray로 변환하면 `<class 'numpy.ndarray'>` 타입의 객체가 생성된다.

또한 `dtype` 속성을 통해 배열에 저장된 데이터의 타입을 확인할 수 있으며, 현재 배열의 원소가 모두 정수이기 때문에 `int64` 타입으로 저장된 것을 확인할 수 있다.

In [10]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2, array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


## 리스트 데이터 타입에 따른 ndarray의 dtype 변화

NumPy에서 `np.array()`를 이용해 리스트를 ndarray로 변환할 때 배열의 데이터 타입(`dtype`)은 리스트에 포함된 원소들의 타입을 기반으로 자동으로 결정된다.

첫 번째 예제에서는 리스트 `list2`에 정수와 문자열이 함께 포함되어 있다.  
NumPy 배열은 하나의 동일한 데이터 타입을 가져야 하므로, 문자열이 포함된 경우 모든 원소가 문자열 타입으로 변환된다.  
따라서 배열의 `dtype`은 문자열 타입으로 결정된다.

두 번째 예제에서는 리스트 `list3`에 정수와 실수가 함께 포함되어 있다.  
NumPy는 정수와 실수를 함께 표현할 수 있는 타입인 **실수(float)**로 데이터를 변환한다.  
따라서 배열의 `dtype`은 `float64`로 설정된다.

이를 통해 NumPy 배열은 하나의 통일된 데이터 타입을 유지하도록 자동으로 타입을 변환한다는 것을 확인할 수 있다.

In [11]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1=np.array([1.1, 2.1, 3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


## ndarray의 데이터 타입 변환 (astype)

NumPy 배열은 `astype()` 메서드를 이용하여 배열의 데이터 타입을 다른 타입으로 변환할 수 있다.

첫 번째 코드에서는 정수형 배열 `array_int`를 생성한 후 `astype('float64')`를 이용하여 실수형 배열로 변환하였다.  
그 결과 배열의 값은 그대로 유지되지만 데이터 타입은 `float64`로 변경된 것을 확인할 수 있다.

두 번째 코드에서는 실수형 배열을 `astype('int32')`를 이용하여 정수형 배열로 변환하였다.  
이때 실수 값은 정수로 변환되면서 **소수점 이하가 제거(truncation)** 된다.

세 번째 코드에서는 실수 값을 가진 배열을 정수형으로 변환하였다.  
이 경우에도 소수점 부분이 제거되어 정수 값만 남게 되는 것을 확인할 수 있다.

이를 통해 `astype()` 메서드를 이용하면 ndarray의 데이터 타입을 원하는 타입으로 변환할 수 있으며, 실수를 정수로 변환할 경우 소수점 이하 값은 제거된다는 것을 확인할 수 있다.

In [12]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


## ndarray 생성과 배열 정보 확인

NumPy에서는 `arange()` 함수를 이용하여 일정한 간격의 숫자를 가지는 배열을 쉽게 생성할 수 있다.  
`np.arange(n)`은 0부터 n-1까지의 값을 가지는 ndarray를 생성한다.

위 코드에서는 `np.arange(10)`을 이용하여 0부터 9까지의 값을 가지는 배열을 생성하였다.  
생성된 배열을 출력하면 `[0 1 2 3 4 5 6 7 8 9]` 형태의 배열이 생성된 것을 확인할 수 있다.

또한 `dtype` 속성을 이용하면 배열에 저장된 데이터 타입을 확인할 수 있으며,  
`shape` 속성을 이용하면 배열의 구조를 확인할 수 있다.

이 배열은 0부터 9까지의 정수로 이루어진 배열이므로 `dtype`은 `int64`이며,  
원소가 10개인 1차원 배열이기 때문에 `shape` 값은 `(10,)`으로 나타난다.

In [13]:
zero_array=np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## 특정 값으로 채워진 ndarray 생성 (zeros, ones)

NumPy에서는 `zeros()`와 `ones()` 함수를 이용하여 특정 값으로 채워진 배열을 생성할 수 있다.

`np.zeros(shape)` 함수는 지정한 shape 형태의 배열을 생성하고 모든 값을 0으로 초기화한다.  
위 코드에서는 `(3,2)` 형태의 배열을 생성하고 `dtype='int32'`를 지정하여 정수형 배열로 생성하였다.

따라서 3행 2열 구조의 배열이 생성되며 모든 원소 값은 0으로 채워진다.

또한 `np.ones(shape)` 함수는 지정한 shape 형태의 배열을 생성하고 모든 값을 1로 채운다.  
위 코드에서는 `(3,2)` 형태의 배열을 생성하였으며 dtype을 따로 지정하지 않았기 때문에 기본적으로 `float64` 타입으로 생성된다.

이를 통해 NumPy에서는 `zeros()`와 `ones()` 함수를 이용하여 원하는 형태의 배열을 쉽게 생성할 수 있으며, `shape`와 `dtype`을 통해 배열의 구조와 데이터 타입을 확인할 수 있다.

In [14]:
array1 = np.arange(10)
print('array1:\n',array1)

array2=array1.reshape(2,5)
print('array2:\n', array2)

array3=array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## ndarray의 형태 변경 (reshape)

NumPy에서는 `reshape()` 함수를 이용하여 배열의 형태(shape)를 변경할 수 있다.  
`reshape()`는 배열의 전체 원소 개수를 유지하면서 배열의 구조를 다른 형태로 변환한다.

먼저 `np.arange(10)`을 이용하여 0부터 9까지의 값을 가지는 1차원 배열을 생성하였다.  
이 배열의 shape는 `(10,)`으로 원소가 10개인 1차원 배열이다.

이후 `reshape(2,5)`를 사용하면 10개의 원소를 **2행 5열 구조의 2차원 배열**로 변환할 수 있다.  
마찬가지로 `reshape(5,2)`를 사용하면 같은 데이터를 **5행 2열 구조의 배열**로 변환할 수 있다.

이처럼 `reshape()` 함수는 배열의 원소 개수를 유지하면서 다양한 형태의 배열 구조로 변환할 때 사용된다.

In [15]:
array1. reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

## reshape 사용 시 오류 발생 예시

NumPy의 `reshape()` 함수는 배열의 형태(shape)를 변경할 때 사용된다.  
하지만 배열의 전체 원소 개수는 변경될 수 없으며, reshape으로 변환하려는 배열의 구조는 기존 원소 개수와 일치해야 한다.

위 코드에서는 `np.arange(10)`으로 생성된 배열을 `(4,3)` 형태로 변환하려고 하였다.  
그러나 해당 배열은 총 10개의 원소를 가지고 있으며 `(4,3)` 구조는 총 12개의 원소가 필요하다.

따라서 reshape을 수행할 수 없으며 **ValueError**가 발생하게 된다.

즉 reshape을 사용할 때는 다음 조건을 만족해야 한다.

원소 개수 = 행 × 열

현재 배열의 경우

10 ≠ 4 × 3

이므로 reshape이 불가능하다.

In [16]:
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3=array1. reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


## reshape에서 -1을 이용한 자동 차원 계산

NumPy의 `reshape()` 함수는 배열의 형태를 변경할 때 사용되며, `-1`을 사용하면 해당 차원의 크기를 자동으로 계산할 수 있다.

먼저 `np.arange(10)`을 이용하여 0부터 9까지의 값을 가지는 1차원 배열을 생성하였다.

이후 `reshape(-1,5)`를 사용하면 열의 개수를 5로 고정하고 행의 개수는 NumPy가 자동으로 계산한다.  
전체 원소 개수는 10개이므로 10 ÷ 5 = 2가 되어 `(2,5)` 형태의 배열이 생성된다.

반대로 `reshape(5,-1)`을 사용하면 행의 개수를 5로 고정하고 열의 개수를 자동으로 계산한다.  
따라서 10 ÷ 5 = 2가 되어 `(5,2)` 형태의 배열이 생성된다.

이처럼 `-1`을 사용하면 배열의 전체 원소 개수를 유지하면서 특정 차원을 자동으로 계산하여 배열의 형태를 변경할 수 있다.

In [18]:
array1=np.arange(10)
array4=array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

## reshape에서 -1 사용 시 발생하는 오류

NumPy의 `reshape()` 함수에서 `-1`을 사용하면 해당 차원의 크기를 자동으로 계산할 수 있다.  
하지만 reshape을 수행할 때는 배열의 전체 원소 개수와 새로운 배열의 구조가 반드시 일치해야 한다.

위 코드에서는 `np.arange(10)`을 이용하여 0부터 9까지 총 10개의 원소를 가지는 배열을 생성하였다.

이후 `reshape(-1,4)`를 수행하면 열의 개수를 4로 고정하고 행의 개수를 자동으로 계산하게 된다.  
그러나 전체 원소 개수는 10개이며 4열 구조를 만들기 위해서는 원소 개수가 4의 배수여야 한다.

즉,

10 ÷ 4 = 2.5

가 되어 정수 형태의 배열 구조를 만들 수 없기 때문에 reshape을 수행할 수 없으며  
**ValueError가 발생하게 된다.**

In [20]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\ n', array5.tolist())
print('array5 shape:', array5. shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1,1)
print('array6:\ n', array6.tolist())
print('array6 shape:', array6. shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:\ n [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:\ n [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


## 다차원 ndarray 생성과 reshape을 이용한 차원 변환

먼저 `np.arange(8)`을 이용하여 0부터 7까지의 값을 가지는 1차원 배열을 생성하였다.  
이 배열은 총 8개의 원소를 가지며 shape는 `(8,)`이다.

이후 `reshape((2,2,2))`를 이용하여 배열을 3차원 배열로 변환하였다.  
즉, 8개의 데이터를 **2 × 2 × 2 구조의 3차원 배열**로 재구성한 것이다.

다음으로 `reshape(-1,1)`을 사용하여 3차원 배열을 2차원 배열로 변환하였다.  
`-1`은 해당 차원의 크기를 자동으로 계산하도록 하는 기능이며, 전체 원소 개수는 8개이므로 `(8,1)` 구조의 배열이 생성된다.

마지막으로 1차원 배열을 `reshape(-1,1)`을 이용하여 2차원 배열로 변환하였다.  
이 경우에도 원소 개수는 8개이므로 `(8,1)` 형태의 2차원 배열이 생성된다.

이를 통해 `reshape()`을 이용하면 배열의 원소 개수를 유지하면서 다양한 차원의 배열로 변환할 수 있음을 확인할 수 있다.

In [22]:
#1부터 9까지의 1차원 ndarray 생성
array1=np.arange(start=1, stop=10)
print('array1:', array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value=array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


## ndarray의 인덱싱(Indexing)

NumPy 배열에서도 파이썬 리스트와 마찬가지로 **인덱싱(Indexing)**을 이용하여 특정 위치의 데이터를 조회할 수 있다.  
인덱스는 0부터 시작하며 배열의 각 원소는 인덱스를 통해 접근할 수 있다.

먼저 `np.arange(start=1, stop=10)`을 이용하여 1부터 9까지의 값을 가지는 1차원 ndarray를 생성하였다.

이후 `array1[2]`를 사용하여 배열의 세 번째 위치에 있는 값을 조회하였다.  
인덱스는 0부터 시작하기 때문에 `array1[2]`는 배열에서 세 번째 값인 **3**을 의미한다.

또한 해당 값을 `value` 변수에 저장하고 `type()` 함수를 이용하여 데이터 타입을 확인하였다.  
그 결과 반환되는 값은 NumPy 배열이 아니라 **numpy의 정수형 스칼라 값(numpy.int64)**임을 확인할 수 있다.

In [23]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


## 음수 인덱스를 이용한 ndarray 접근

NumPy 배열에서는 음수 인덱스를 이용하여 배열의 뒤쪽 원소에 접근할 수 있다.  
음수 인덱스는 배열의 마지막 원소부터 역순으로 접근할 때 사용된다.

예를 들어 `-1`은 배열의 마지막 원소를 의미하고, `-2`는 뒤에서 두 번째 원소를 의미한다.

위 코드에서는 `array1[-1]`을 이용하여 배열의 마지막 값인 9를 조회하였고,  
`array1[-2]`를 이용하여 뒤에서 두 번째 값인 8을 조회하였다.

이처럼 음수 인덱스를 사용하면 배열의 끝에서부터 데이터를 쉽게 조회할 수 있다.

In [24]:
array1[0]=9
array1[8]=0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


## ndarray의 값 수정 (Indexing을 이용한 데이터 변경)

NumPy 배열에서는 인덱싱(Indexing)을 이용하여 특정 위치의 데이터를 조회할 뿐만 아니라 값을 수정할 수도 있다.

위 코드에서는 먼저 `array1[0] = 9`를 통해 배열의 첫 번째 위치에 있는 값을 9로 변경하였다.  
NumPy 배열의 인덱스는 0부터 시작하기 때문에 `array1[0]`은 배열의 첫 번째 원소를 의미한다.

또한 `array1[8] = 0`을 이용하여 배열의 마지막 위치에 있는 값을 0으로 변경하였다.

이처럼 NumPy 배열은 인덱스를 이용하여 특정 위치의 값을 직접 수정할 수 있으며, 수정된 결과는 배열에 즉시 반영된다.

In [25]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:',  array2d[0,0])
print('(row=0, col=1) index 가리키는 값:',  array2d[0,1])
print('(row=1, col=0) index 가리키는 값:',  array2d[1,0])
print('(row=2, col=2) index 가리키는 값:',  array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


## 2차원 ndarray의 인덱싱(Indexing)

NumPy 배열이 2차원 구조일 경우에는 행(row)과 열(column) 인덱스를 이용하여 특정 위치의 값을 조회할 수 있다.

먼저 `np.arange(start=1, stop=10)`을 이용하여 1부터 9까지의 값을 가지는 1차원 배열을 생성하였다.  
이후 `reshape(3,3)`을 이용하여 배열을 3행 3열 형태의 2차원 배열로 변환하였다.

2차원 배열에서는 `array[row, column]` 형태의 인덱싱을 사용하여 특정 위치의 값을 조회할 수 있다.

예를 들어 `array2d[0,0]`은 첫 번째 행과 첫 번째 열의 값을 의미하며,  
`array2d[0,1]`은 첫 번째 행과 두 번째 열의 값을 의미한다.

이처럼 2차원 ndarray에서는 행과 열 인덱스를 이용하여 배열의 특정 위치에 있는 데이터를 쉽게 조회할 수 있다.

In [26]:
array1 = np.arange(start=1, stop=10)
array3 = array1[1:3]
print(array3)
print(type(array3))

[2 3]
<class 'numpy.ndarray'>


## ndarray의 슬라이싱(Slicing)

NumPy 배열에서는 슬라이싱(Slicing)을 이용하여 배열의 특정 범위에 있는 데이터를 조회할 수 있다.  
슬라이싱은 `array[start:end]` 형태로 사용하며, start 인덱스부터 end 인덱스 직전까지의 값을 반환한다.

위 코드에서는 `np.arange(start=1, stop=10)`을 이용하여 1부터 9까지의 값을 가지는 1차원 ndarray를 생성하였다.

이후 `array1[1:3]`을 사용하여 인덱스 1부터 인덱스 3 이전까지의 데이터를 조회하였다.  
따라서 배열에서 두 번째 값과 세 번째 값인 `[2, 3]`이 반환된다.

또한 슬라이싱을 통해 반환되는 결과 역시 NumPy 배열 형태이므로 `type()`을 확인하면 `numpy.ndarray` 타입임을 확인할 수 있다.

In [27]:
array1=np.arange(start=1, stop=10)
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


## ndarray 슬라이싱에서 시작과 끝 인덱스 생략

NumPy 배열에서는 슬라이싱을 사용할 때 시작 인덱스(start)나 끝 인덱스(end)를 생략할 수 있다.

먼저 `np.arange(start=1, stop=10)`을 이용하여 1부터 9까지의 값을 가지는 1차원 ndarray를 생성하였다.

`array1[:3]`은 시작 인덱스를 생략하고 끝 인덱스만 지정한 경우로, 배열의 처음부터 인덱스 3 이전까지의 값을 반환한다.  
따라서 `[1, 2, 3]`이 반환된다.

`array1[3:]`은 시작 인덱스만 지정하고 끝 인덱스를 생략한 경우로, 인덱스 3부터 배열의 끝까지의 값을 반환한다.  
따라서 `[4, 5, 6, 7, 8, 9]`가 반환된다.

`array1[:]`은 시작과 끝 인덱스를 모두 생략한 경우로 배열 전체를 반환한다.  
즉 원래 배열과 동일한 결과가 출력된다.

이처럼 슬라이싱에서 시작 또는 끝 인덱스를 생략하면 배열의 처음이나 끝까지의 데이터를 쉽게 조회할 수 있다.

In [28]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


## 2차원 ndarray의 슬라이싱(Slicing)

NumPy의 2차원 배열에서는 행(row)과 열(column)을 이용하여 슬라이싱을 수행할 수 있다.  
슬라이싱은 `array[row_start:row_end, col_start:col_end]` 형태로 사용하며, 시작 인덱스 이상부터 끝 인덱스 이전까지의 값을 반환한다.

먼저 `np.arange(start=1, stop=10)`을 이용하여 1부터 9까지의 값을 가지는 1차원 배열을 생성하였다.  
이후 `reshape(3,3)`을 이용하여 배열을 3행 3열의 2차원 배열로 변환하였다.

`array2d[0:2, 0:2]`는 0~1행과 0~1열에 해당하는 부분 배열을 반환한다.  
`array2d[1:3, 0:3]`는 1~2행과 전체 열을 선택하여 부분 배열을 반환한다.

`array2d[1:3, :]`은 1~2행의 모든 열을 선택하는 슬라이싱이며,  
`array2d[:, :]`은 전체 행과 전체 열을 선택하여 원본 배열과 동일한 결과를 반환한다.

또한 `array2d[:2, 1:]`은 처음 두 행과 두 번째 열 이후의 데이터를 선택한다.  
마지막으로 `array2d[:2, 0]`은 첫 번째 열의 처음 두 행 데이터를 선택하며, 이 경우 결과는 1차원 배열로 반환된다.

이처럼 2차원 ndarray에서는 행과 열을 동시에 지정하여 다양한 부분 배열을 쉽게 추출할 수 있다.

In [29]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


## 2차원 ndarray에서 행(Row) 인덱싱

NumPy의 2차원 배열에서는 인덱싱을 이용하여 특정 행(row)을 조회할 수 있다.  
배열에서 `array[index]` 형태로 접근하면 해당 행의 데이터를 반환한다.

위 코드에서는 `array2d[0]`을 이용하여 첫 번째 행의 데이터를 조회하였고,  
`array2d[1]`을 이용하여 두 번째 행의 데이터를 조회하였다.

2차원 배열에서 특정 행을 선택하면 해당 행의 모든 열 데이터가 반환되며,  
이때 반환되는 결과는 2차원 배열이 아니라 **1차원 ndarray** 형태로 반환된다.

따라서 `array2d[0]`과 `array2d[1]`의 shape를 확인하면 `(3,)` 형태의 1차원 배열임을 확인할 수 있다.

In [32]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3, 3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2] => ',array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2] => ',array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1],2] =>  [3, 6]
array2d[[0,1],0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


## 2차원 ndarray에서 행(Row) 인덱싱

NumPy의 2차원 배열에서는 인덱싱을 이용하여 특정 행(row)을 조회할 수 있다.  
배열에서 `array[index]` 형태로 접근하면 해당 행의 데이터를 반환한다.

위 코드에서는 `array2d[0]`을 이용하여 첫 번째 행의 데이터를 조회하였고,  
`array2d[1]`을 이용하여 두 번째 행의 데이터를 조회하였다.

2차원 배열에서 특정 행을 선택하면 해당 행의 모든 열 데이터가 반환되며,  
이때 반환되는 결과는 2차원 배열이 아니라 **1차원 ndarray** 형태로 반환된다.

따라서 `array2d[0]`과 `array2d[1]`의 shape를 확인하면 `(3,)` 형태의 1차원 배열임을 확인할 수 있다.

2차원 ndarray에서 Fancy Indexing
NumPy에서는 Fancy Indexing을 이용하여 특정 행(row)이나 열(column)을 선택할 수 있다.
Fancy Indexing은 리스트 형태의 인덱스를 사용하여 원하는 위치의 데이터를 선택하는 방식이다.
위 코드에서는 array2d[[0,1]]과 같은 형태로 여러 개의 행을 동시에 선택하는 예제를 보여준다.
먼저 array2d 배열은 다음과 같은 구조를 가진다.
array2d

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape
(3,3)
즉 3행 3열의 2차원 배열이다.

In [33]:
array1d=np.arange(start=1,stop=10)
#[ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값 :', array3)
array1d>5

array1d>5 불린 인덱싱 결과 값 : [6 7 8 9]


array([False, False, False, False, False,  True,  True,  True,  True])

## Boolean Indexing

NumPy에서는 **Boolean Indexing**을 이용하여 특정 조건을 만족하는 데이터만 선택할 수 있다.  
Boolean Indexing은 배열에 조건식을 적용하여 **True인 위치의 값만 추출하는 방법**이다.

먼저 `array1d` 배열을 생성한다.

array1d

[1 2 3 4 5 6 7 8 9]

다음으로 조건식 `array1d > 5`를 적용하면 각 원소에 대해 조건을 검사하여  
True 또는 False 값을 가지는 **Boolean 배열**이 생성된다.

array1d > 5

[False False False False False True True True True]

이 Boolean 배열을 이용하여 인덱싱을 수행하면 **True에 해당하는 값만 선택**된다.

```python
array3 = array1d[array1d>5]

In [34]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

불린 인덱스로 필터링 결과 : [6 7 8 9]
일반 인덱스로 필터링 결과 : [6 7 8 9]


## Boolean Indexing과 Fancy Indexing

이 코드는 NumPy에서 **Boolean Indexing**과 **Fancy Indexing**을 이용하여 배열의 특정 값을 선택하는 방법을 보여준다.

먼저 Boolean 배열을 이용하여 인덱싱을 수행한다.

```python
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]

In [36]:
org_array=np.array([3,1,9,5])
print('원본 행렬:', org_array)

# np.sort()로 정렬 _ 원 행렬 유지
sort_array1=np.sort(org_array)
print('np.sort()호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort()호출 후 원본 행렬:', org_array)

# ndarray.sort()로 정렬 _ 정렬된 원 행렬
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행령:', org_array)

원본 행렬: [3 1 9 5]
np.sort()호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort()호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행령: [1 3 5 9]


## NumPy 배열 정렬

NumPy에서는 배열을 정렬하기 위해 `np.sort()` 함수와 `ndarray.sort()` 메소드를 사용할 수 있다.  
두 방법 모두 배열을 정렬하는 기능을 제공하지만 **원본 배열이 변경되는지 여부에서 차이가 있다.**

먼저 다음과 같은 1차원 배열을 생성한다.

[3 1 9 5]

---

### np.sort()를 이용한 정렬

`np.sort()` 함수는 배열을 정렬한 **새로운 배열을 반환**하며, 원본 배열은 변경되지 않는다.

예를 들어 `np.sort(org_array)`를 호출하면 다음과 같은 정렬된 배열이 반환된다.

[1 3 5 9]

하지만 이 경우 원본 배열 `org_array`는 그대로 유지된다.

[3 1 9 5]

---

### ndarray.sort()를 이용한 정렬

`ndarray.sort()` 메소드는 배열 자체를 직접 정렬하는 방식이다.  
즉, 정렬 결과가 **원본 배열에 그대로 반영된다.**

`org_array.sort()`를 실행하면 원본 배열은 다음과 같이 변경된다.

[1 3 5 9]

또한 `ndarray.sort()` 메소드는 정렬된 배열을 반환하지 않기 때문에 반환값은 `None`이다.

---

### 정리

NumPy 배열 정렬 방법의 차이는 다음과 같다.

- `np.sort()` : 정렬된 **새로운 배열 반환**, 원본 배열 유지  
- `ndarray.sort()` : **원본 배열 자체 정렬**, 반환값 없음

In [37]:
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


### 내림차순 정렬

NumPy에서 `np.sort()` 함수는 기본적으로 **오름차순(ascending)** 정렬을 수행한다.  
하지만 슬라이싱을 이용하면 배열을 **내림차순(descending)** 으로 정렬할 수 있다.

먼저 `np.sort()`를 사용하여 배열을 오름차순으로 정렬한다.

[1 3 5 9]

이후 슬라이싱 `[::-1]`을 적용하면 배열의 순서를 뒤집을 수 있다.

`[::-1]`은 배열을 **역순(reverse order)** 으로 뒤집는 슬라이싱 방식이다.

```python
np.sort(org_array)[::-1]
```

따라서 정렬된 배열을 뒤집으면 다음과 같이 **내림차순 정렬 결과**를 얻을 수 있다.

[9 5 3 1]

In [39]:
array2d=np.array([[8,12],[7,1]])
sort_array2d_axis0=np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d, axis=1)
print('로우 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
로우 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


## NumPy 2차원 배열 정렬 (axis 옵션)

NumPy에서는 `np.sort()` 함수의 `axis` 옵션을 이용하여 2차원 배열을 특정 방향으로 정렬할 수 있다.

다음과 같은 배열이 있다고 가정한다.

[[8 12]  
 [7  1]]

### axis=0 정렬

`axis=0`은 열(column)을 기준으로 정렬하는 것을 의미한다.  
즉, 같은 열에 있는 값들을 위에서 아래 방향으로 정렬한다.

```python
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)
```

정렬 결과

[[ 7  1]  
 [ 8 12]]

---

### axis=1 정렬

`axis=1`은 행(row)을 기준으로 정렬하는 것을 의미한다.  
즉, 각 행 내부에서 왼쪽에서 오른쪽 방향으로 정렬이 이루어진다.

```python
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('로우 방향으로 정렬:\n', sort_array2d_axis1)
```

정렬 결과

[[ 8 12]  
 [ 1  7]]

---

### 정리

- `axis=0` : 열(column) 기준 정렬  
- `axis=1` : 행(row) 기준 정렬

In [40]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


## np.argsort()

NumPy에서는 배열을 정렬할 때 `np.sort()`를 사용하면 정렬된 값이 반환된다.  
하지만 `np.argsort()`를 사용하면 **정렬된 값의 인덱스(index)** 가 반환된다.

예를 들어 다음과 같은 배열이 있다고 가정한다.

[3 1 9 5]

`np.argsort()`를 적용하면 배열의 값이 정렬될 때 **원래 배열에서의 위치(index)** 가 반환된다.

```python
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)
```

정렬된 배열은 다음과 같다.

[1 3 5 9]

이때 정렬된 값의 **원래 위치(index)** 는 다음과 같다.

1 → index 1  
3 → index 0  
5 → index 3  
9 → index 2  

따라서 `np.argsort()`의 결과는 다음과 같다.

[1 0 3 2]

즉 `np.argsort()`는 **정렬된 값의 위치 정보를 반환하는 함수**이다.

In [41]:
org_array=([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


## np.argsort()를 이용한 내림차순 정렬 인덱스

`np.argsort()` 함수는 배열을 정렬할 때 **정렬된 값의 인덱스(index)** 를 반환한다.  
기본적으로 `np.argsort()`는 **오름차순 기준의 인덱스**를 반환한다.

예를 들어 다음과 같은 배열이 있다고 가정한다.

[3 1 9 5]

`np.argsort()`를 적용하면 오름차순 정렬 시 원본 배열의 인덱스가 반환된다.

[1 0 3 2]

이는 다음과 같은 의미를 가진다.

1 → index 1  
3 → index 0  
5 → index 3  
9 → index 2  

내림차순 정렬 기준의 인덱스를 구하기 위해서는 슬라이싱 `[::-1]`을 사용하여 결과를 뒤집는다.

```python
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)
```

이 경우 결과는 다음과 같다.

[2 3 0 1]

즉, `np.argsort()`로 구한 오름차순 인덱스를 뒤집으면 **내림차순 정렬 기준의 인덱스**를 얻을 수 있다.

In [43]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


## np.argsort()를 이용한 배열 정렬과 데이터 매칭

`np.argsort()` 함수는 배열을 정렬할 때 **정렬된 값의 인덱스(index)** 를 반환한다.  
이 인덱스를 이용하면 **다른 배열의 데이터를 같은 기준으로 정렬**할 수 있다.

다음과 같이 학생 이름과 성적을 각각 배열로 생성한다.

```
name_array  = ['John', 'Mike', 'Sarah', 'Kate', 'Samuel']
score_array = [78, 95, 84, 98, 88]
```

먼저 `np.argsort()`를 사용하여 성적을 기준으로 **오름차순 정렬 시 인덱스**를 구한다.

```python
sort_indices_asc = np.argsort(score_array)
```

성적을 오름차순으로 정렬하면 다음과 같은 순서가 된다.

```
78 → 84 → 88 → 95 → 98
```

이때 원래 배열에서의 인덱스는 다음과 같다.

```
[0 2 4 1 3]
```

이 인덱스를 `name_array`에 적용하면 **성적 순서에 맞게 이름도 함께 정렬**할 수 있다.

```python
name_array[sort_indices_asc]
```

결과

```
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
```

즉 `np.argsort()`는 **정렬 기준이 되는 배열의 인덱스를 구한 후 다른 배열에도 같은 순서를 적용할 때 유용하게 사용된다.**

In [44]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8],[9,10],[11,12]])
dot_product=np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


## NumPy 행렬 내적 (Matrix Multiplication)

NumPy에서는 `np.dot()` 함수를 사용하여 두 행렬의 **행렬 내적(Matrix Multiplication)** 을 계산할 수 있다.

다음과 같은 두 개의 행렬이 있다고 가정한다.

행렬 A

```
[[1 2 3]
 [4 5 6]]
```

행렬 B

```
[[ 7  8]
 [ 9 10]
 [11 12]]
```

`np.dot(A, B)`를 사용하면 두 행렬의 내적을 계산할 수 있다.

```python
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)
```

행렬 내적은 **A의 행(row)과 B의 열(column)을 곱하여 계산**된다.

예를 들어 첫 번째 원소는 다음과 같이 계산된다.

```
(1×7) + (2×9) + (3×11) = 58
```

같은 방식으로 계산하면 결과 행렬은 다음과 같다.

```
[[ 58  64]
 [139 154]]
```

따라서 `np.dot()` 함수는 두 행렬의 **행렬 곱(Matrix Multiplication)** 결과를 반환한다.

In [45]:
A=np.array([[1,2],[3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]


## NumPy 전치 행렬 (Transpose)

NumPy에서는 `np.transpose()` 함수를 이용하여 **행렬의 전치(transpose)** 를 구할 수 있다.  
전치 행렬은 **행(row)과 열(column)의 위치를 서로 바꾸는 연산**이다.

다음과 같은 행렬 A가 있다고 가정한다.

```
[[1 2]
 [3 4]]
```

`np.transpose()` 함수를 사용하면 행과 열이 서로 바뀐 전치 행렬을 얻을 수 있다.

```python
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)
```

전치 행렬의 결과는 다음과 같다.

```
[[1 3]
 [2 4]]
```

즉, 원래 행렬의 행과 열이 서로 교환되어 새로운 행렬이 생성된다.