In [1]:
import numpy as np

In [2]:
#np.array함수를 통해 ndarray(다차원 배열)로 변환
array1 = np.array([1, 2, 3])
print('array1 type:',type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                   [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)\

#리스트의 리스트 [[]]는 2차원이므로 array1과 다른 결과가 나온다
array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [4]:
#array.ndim을 통해 각 array의 차원을 확인
print('array1:{0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,array2.ndim, array3.ndim))


array1:1차원, array2: 2차원, array3: 2차원


In [5]:
#list를 ndarray로 바꿔준 후 .dtype함수로 ndarray내의 자료형을 확인
list1= [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)


<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [7]:
'''정수형과 문자열이 섞여있는 list를 ndarray로 변환하면 
모두 같은 자료형이여야 하므로 더 큰 자료형으로 바뀌어서
정수형이 문자형으로 바뀌어 나옴'''

list2 = [ 1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)


['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [8]:
#.astype()을 통해 int32를 float64로 변환하고 다시 int32로 변경한다 float를 int형으로 변경할때 소수점 이하는 다 없어진다.
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [9]:
#arange함수를 통해 0부터 함수 인자  값 -1까지의 값을 순차적으로 ndarray의 데이터 값으로 변환해준다
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)


[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [10]:
#zeros()를 통해 모든 값을 0으로 채운 해당 shape을 가진 ndarray를 만든다 이때 dtype을 지정해주지 않으면 float64형으로 채운다.
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

#ones()도 zeros()와 유사하게 모든 값을 1로 채운 해당 shape을 가진 ndarray를 만든다 이때 dtype을 지정해주지 않으면 float64형으로 채운다.
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)


[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [13]:
array1 = np.arange(10)
print('array1:\n', array1)

#reshape()를 통해 ndarray의 차원과 크기를 변경 
array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)



array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [14]:
#단 (10,)을 (4,3)과 같은 shape로 변경 불가능하다.
array1.reshape(4,3)


ValueError: cannot reshape array of size 10 into shape (4,3)

In [16]:
array1 = np.arange(10)
print(array1)
#(-1,5)에서 -1은 열은 5칸으로 픽스하고 행은 남은 데이터 개수에 딱 맞아떨어지게 알아서 설정해주는것
array2=array1.reshape(-1,5)
print('array2 shape:', array2.shape)
#(5,-1)도 마찬가지로 행은 5칸으로 픽스하고 열은 남은 데이터 개수에 딱 맞아떨어지게 알아서 설정해주는것
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)




[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [17]:
#10개의 데이터인데 열을 4칸으로 픽스하면 행이 안 맞아떨어지므로 error가 뜬다.
array1 = np.arange(10)
array4 = array1.reshape(-1,4)


ValueError: cannot reshape array of size 10 into shape (4)

In [19]:
#toolist()를 이용해 리스트 자료형으로 바꿀수 있다.(print를 이용해서 출력할때 시각적으로 더 이해하기 쉬울수 있기 때문)
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5::\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5::
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [21]:
#단일 값 추출
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))


array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [22]:
#인덱스에 마이너스 기호를 이용하면 맨 뒤에서부터 데이터를 추출할 수 있다.
print('맨 뒤의 값:"', array1[-1], ' 맨 뒤에서 두 번째 값:', array1[-2])


맨 뒤의 값:" 9  맨 뒤에서 두 번째 값: 8


In [23]:
#단일 인덱스를 이용해 ndarray 내의 데이터값도 수정 가능하다.
array1[0] = 9
array1[8] = 0
print('array1:', array1)


array1: [9 2 3 4 5 6 7 8 0]


In [24]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

# [0,0]은 1행 1열의 데이터를 인덱스하는 것으로 인덱스를 통해 데이터 추출이 가능하다
print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('{row=2, col=2) index 가리키는 값:', array2d[2,2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
{row=2, col=2) index 가리키는 값: 9


In [26]:
array1 = np.arange(start=1, stop=10)
#슬라이싱은 종료 인덱스 -1의 위치에 있는 데이터까지 ndarray를 반환한다.
array3 = array1[0:3]
print(array3)
print(type(array3))


[1 2 3]
<class 'numpy.ndarray'>


In [28]:
# ':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주합니다.
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

#'기호' 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주합니다.
array5=array1[3:]
print(array5)

#':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주합니다.
array6 = array1[:]
print(array6)


[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [33]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

#0번부터 1번 행까지, 0번부터 1번 열까지 가져오기
print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
#1번부터 2번 행까지, 0번부터 2번 열까지 가져오기
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
#1번부터 2번 행까지, 모든 열가져오기
print('array2d[1:3, :] \n', array2d[1:3, :])
#모든행과 모든 열을 가져오기
print('array2d[:, :]\n', array2d[:, :])
#0번부터 1번 행까지, 1번부터 끝열까지 가져오기
print('array2d[:2, 1:] \n', array2d[:2, 1:])
#0번부터 1번 행까지, 0번 열만 가져오기
print('array2d[:2, 0] \n', array2d[:2, 0])



array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [34]:
#[]로 행만 뽑을수 있다.
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [35]:
#팬시 인덱싱
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

#0번 1번의 행을가져오고 2번열을 가져오는것
array3 = array2d[[0, 1],2]
print('array2d[[0,1],2] =>', array3.tolist())

#0번 1번의 행을 가져오고 0번부터 1번까지의 열을 가져오는것
array4 = array2d[[0,1], 0:2]
print('array2d[0, 1], 0:2] =>', array4.tolist())

#0번 1번 행을 다가져오는 것
array5 = array2d[[0, 1]]
print('array2d[0,1] => ', array5.tolist())


array2d[[0,1],2] => [3, 6]
array2d[0, 1], 0:2] => [[1, 2], [4, 5]]
array2d[0,1] =>  [[1, 2, 3], [4, 5, 6]]


In [36]:
#불린 인덱싱
array1d= np.arange(start=1, stop=10)
#[] 안에 array1d > 5 Boolean indexing을 적용
#True 판정을 받은 자리에 있던 숫자들만 값으로 나오게된다.
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)


array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [37]:
array1d > 5


array([False, False, False, False, False,  True,  True,  True,  True])

In [38]:
#불린d 인덱스로 필터링 하면 동일한 데이터 세트가 반환된다.
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)


불린 인덱스로 필터링 결과 : [6 7 8 9]


In [40]:
#일반 인덱스로 필터링 할때
indexes = np.array([5, 6, 7, 8])
array4 = array1[indexes]
print('일반 인덱스로 필터링 결과:', array4)


일반 인덱스로 필터링 결과: [6 7 8 9]


In [42]:
org_array=np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)
#np.sort()로 정렬
#np.sort()로 정렬하면 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환한다.
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
# ndarray.sort()로 정렬
# ndarray.sort()로 정렬하게 되면 원행렬 자체를 정렬한 형태로 변환
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)




원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [43]:
#내림차순으로 정렬하기 위해서는 [::-1]을 적용
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)


내림차순으로 정렬: [9 5 3 1]


In [44]:
array2d = np.array([[8, 12],
                    [7, 1]])

#열 방향으로 작은 숫자가 위로 정렬함
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

#행 방향으로 작은 숫자가 왼쪽으로 가도록 정렬
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)




로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [45]:
#.argsort()는 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환함
org_array = np.array([3, 1, 9 ,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)


<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [46]:
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)


행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [47]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kat', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

#np.argsort(score_array)를 이용해 반환된 인덱스를 name_array에 팬시 인덱스로 적용해 추출할 수 있다.
sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])



성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kat']


In [49]:
#np.dot()을 이용해 두 행렬의 내적을 계산할 수 있다.
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)


행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [50]:
#np.transpose()를 이용해 전치 행렬을 구할 수 있다.
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)


A의 전치 행렬:
 [[1 3]
 [2 4]]
