## Numpy ndarray 개요
넘파이는 다차원 배열 쉽게 생성 및 다양한 연산 가능

In [84]:
import numpy as np #np라고 관례적으로 줄여서 씀

In [86]:
# 1차원 
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:',array1.shape)
# 2차원 (2개 로우, 3개 컬럼)
array2=np.array([[1,2,3],
                 [4,5,6]])
print('array2 type:', type(array2))
print('array2 array 형태:',array2.shape)

# 2차원 (1개 로우, 3개 컬럼)
array3=np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [16]:
print('array1: {0}차원, array2: {1}차원, array3:{2}차원'. format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:2차원


ndarray는 int, float, unsigned int등 다양한 형 가능. 하지만 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능
즉, 한개의 ndarray에 다른 데이터 형 같이 있을 수 없음. 
같이 있으면 더 큰걸로 변환됨


In [18]:
list1 = [1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1, array1.dtype)


<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


list자료형을 ndarray로 쉽게 변경할 수 있음. 이러면 안에 있는 데이터 값은 모두 int32형이 됨.

### astype을 통애서 ndarray안에서 데이터 타입 변경이 가능함.

In [22]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


## arange, zeros, ones

arange는 array를 range로 표현하는 거임. 0부터 함수 인자값 -1까지의 값을 순차적으로 ndarray값으로 변환해줌

In [26]:
sequence_array=np.arange(10)
print(sequence_array) #이러면 자동으로 채워짐 (0부터 10-1 까지 )
print(sequence_array.dtype, sequence_array.shape)


[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [28]:
zero_array=np.zeros((3,2), dtype='int32') #인자로 받은 shape 형태로 0으로 채움.
print(zero_array)
print(zero_array.dtype,zero_array.shape)

one_array=np.ones((3,2)) #인자로 받은 shape형태로 1로 채움,
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## ndarray의 차원과 크기 변경 reshape()

In [32]:
array1=np.arange(10)
print('array1:\n', array1)

array2=array1.reshape(2,5) #2rows 5columns
print('array2:\n', array2)

array3=array1.reshape(5,2)
print('array3:\n', array3)

#해당 배열을 지정된 형태로 reshape못할 수도 있음. ex)10을 4,3으로 나눈다는 둥

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### -1을 사용한 방법

In [37]:
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5) #칼럼을 5로 하고 row를 알맞게 넣는다.
print(array2.shape)
array3=array1.reshape(5,-1) #row를 5로 하고 칼럼을 알맞게 넣는다.
print(array3.shape)

# 하지만 5나 1이라 되는거지 3같은걸로 하면은 오류가 나옴.

[0 1 2 3 4 5 6 7 8 9]
(2, 5)
(5, 2)


In [43]:
array1= np.arange(8)
array3d=array1.reshape((2,2,2))
print(array3d.tolist())

#3차원을 2차원으로 변환
array5=array3d.reshape(-1,1)
print(array5.tolist())
print(array5.shape)

#1차원을 2차원으로 변환
array6=array1.reshape(-1,1)
print(array6.tolist())
print(array6.shape)


[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
[[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)
[[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)


### 넘파이 차원배열 데이터 세트 선택하기 -인덱스

In [47]:
#단일값 추출
array1=np.arange(start=1, stop=10) #이러면 10은 안들어감.
print(array1)
value=array1[2]
print(value)
print(type(value))

print(array1[-1]) #맨뒤에서 첫번째 값.
#단일 인덱스로 값 추출이 아니라 반대로 수정도 가능함.

[1 2 3 4 5 6 7 8 9]
3
<class 'numpy.int64'>
9


In [50]:
#다차원에서 참조
array1d=np.arange(start=1,stop=10) #10은 안들어감.
array2d=array1d.reshape(3,3)
print(array2d)

print(array2d[0,0]) #row, col순으로 참조
print(array2d[0,1])
print(array2d[1,0])
print(array2d[2,2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
4
9


row와 column은 넘파이에서는 쓰이지 않는 표현임. axis n 이렇게 쓰이는데 2차원에서는 axis 1은 row, axis 2는 column으로 쓰인다. 

In [53]:
#슬라이싱
array1=np.arange(start=1, stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))
#":"앞에 시작 인덱스 생략하면 자동으로 맨 처음 인덱스인 0, 뒤에 종료 인덱스 생략하면 자동으로 마지막 인덱스로 간주


[1 2 3]
<class 'numpy.ndarray'>


In [56]:
#슬라이싱
array1=np.arange(start=1, stop=10)
array4=array1[:3]
print(array3)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

#":"앞에 시작 인덱스 생략하면 자동으로 맨 처음 인덱스인 0, 뒤에 종료 인덱스 생략하면 자동으로 마지막 인덱스로 간주


[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [63]:
#2처원 배열에서 슬라이싱
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0]) #한쪽에는 슬라이싱 하고 다른 한쪽에는 단일 값 넣을 수도 있음.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


### 팬시 인덱싱

In [65]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2] =>', array3.tolist())
array4=array2d[[0,1], 0:2]
print('array2d[[0,1],0:2] =>', array4.tolist())
array5=array2d[[0,1]]
print('array2d[[0,1]]=>', array5.tolist())


array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


### 불린 인덱싱(boolean indexing)

In [70]:
array1d=np.arange(start=1, stop=10)
array3=array1d[array1d>5]
print('array3=',array3)

boolean_index=np.array([False,False,False,False,False,True,True,True,True])
array3=array1d[boolean_index]
print(array3)

#1. 필터링 조건을 기재, 2. False값 무시하고 True 값에 해당하는 인덱스 값만을 저장. 3. 저장된 인덱스 데이터 세트로 ndarray조회

array3= [6 7 8 9]
[6 7 8 9]


### 행렬의 정렬


In [74]:
org_array=np.array([3,1,9,5])
print('원본 행렬: ', org_array)
#np.sort() 로 정렬 -> 원본 변경하지 않음.
sort_array1=np.sort(org_array)
print('np.sort() 호출 반환된 정렬 행렬: ', sort_array1)
print('np.sort() 호출 후 원본 행렬: ', org_array)

# ndarray.sort()로 정렬 원본 자체를 정렬함.
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬: ', sort_array2)
print('org_array.sort() 호출 추 반환된 원본 행렬: ', org_array)

원본 행렬:  [3 1 9 5]
np.sort() 호출 반환된 정렬 행렬:  [1 3 5 9]
np.sort() 호출 후 원본 행렬:  [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬:  None
org_array.sort() 호출 추 반환된 원본 행렬:  [1 3 5 9]


In [82]:
sort_array1_desc=np.sort(org_array)[::-1] #내림차순으로 정렬하려면 이렇게 [::-1] 하면 됨.
print('내림 차순으로 정렬: ', sort_array1_desc)

내림 차순으로 정렬:  [9 5 3 1]


In [ ]:
원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 np.argsort를 이용함.

In [80]:
import numpy as np
name_array=np.array(['John', 'Mike', 'Sarah', 'kate', 'Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array) #agsort:
print('성적 오름차순 정렬 시 score_array의 인덱스: ', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력: ', name_array[sort_indices_asc])
      

성적 오름차순 정렬 시 score_array의 인덱스:  [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력:  ['John' 'Sarah' 'Samuel' 'Mike' 'kate']


In [90]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices)) #오름차순 정렬 인덱스
print('행렬 정렬 시 원본 행렬의 인덱스: ',sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스:  [1 0 3 2]


dot 써서 행렬 내적 

In [93]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8], [9,10], [11,12]])
dot_product=np.dot(A,B) 
print('행렬 내적 결과: \n', dot_product)

행렬 내적 결과: 
 [[ 58  64]
 [139 154]]


전치 행렬: 원 행렬에서 행과 열의 위치를 교환한 원소로 구성한 행렬.

In [ ]:
A=np.array([[1,2],