### Numpy ndarray 개요

CUAI 260309 1주차 

In [2]:
import numpy as np

# 넘파이 사용 위해서 np로 라이브러리를 불러옴. 

In [3]:
# 배열 생성 및 형태(shape) 확인
# 1차원 ndarray 생성
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

# 2차원 ndarray 생성
array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

# 행 1개인 2차원 ndarray 별도 생성 후 차이 확인
array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)







array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [ ]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

# 차원 확인
# .ndim 속성을 통해 몇 차원 배열인지 정수로 반환

array1: 1차원, array2: 2차원, array3: 2차원


In [ ]:
# 파이썬 리스트 만든다. 
list1 = [1,2,3]
print(type(list1))
#np.array 이용해서 리스트를 ndarray로 변환.
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

# 데이터 타입의 형변환 (Upcasting)
# Numpy 배열은 한 가지 데이터 타입만 가짐. 
# 서로 다른 타입이 섞이면 더 큰 데이터 타입(실수형)으로 자동 변환 (예: 숫자 + 문자 -> 모두 문자로 변환)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

# 데이터 타입 변경 (astype)
# .astype('float64') 또는 .astype('int32')를 사용하여 명시적으로 타입을 바꿀 수 있음. 

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

In [4]:
sequence_array = np.arange(10)
print(sequence_array)
# dtype과 shape 정보를 함께 확인 가능. 
print(sequence_array.dtype, sequence_array.shape)

#arange: 0부터 (n-1)까지의 연속된 정수 배열 생성


[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
#zeros & ones: 모든 원소가 0 또는 1인 배열 생성. 
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)


#(shape)를 튜플 형태로 전달해야 함.

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape()

In [ ]:
#  reshape(): 지정한 shape로 배열 구조 변경
# -1 인자 사용: 다른 차원의 크기에 맞춰 자동으로 계산하여 할당. (매우 자주 쓰임!)

# 0-9까지 1차원 배열 생성
array1 = np.arange(10)
print('array1:\n', array1)
# 1차원 배열을 2행 5열 구조로 재배열
array2 = array1.reshape(2,5)
print('array2:\n',array2)
#같은 데이터를 5행 2열 구조로 재배열
array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array1.reshape(4,3)
# 전체 원소 수가 안 맞으면 안됨. 

ValueError: cannot reshape array of size 10 into shape (4,3)

In [ ]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [ ]:
#-1을 사용해도 원소 수 안 맞으면 실패. 
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [ ]:
# 3차원을 2차원으로, 1차원을 2차원으로 변경
# 특히 머신러닝 모델 입력값으로 넣을 때 (데이터 개수, 1) 형태로 맞추기 위해 reshape(-1, 1)을 많이 쓰임.
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱 (indexing)

* 단일 값 추출

In [14]:
# 단일 값 추출: 0부터 시작하는 인덱스로 접근. 음수 인덱스는 뒤에서부터 역순.

# 1에서 부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [ ]:
# 음수 인덱스 사용시, 뒤쪽 원소를 쉽게 참조. 
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [16]:
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [ ]:
# 1차원 배열 후에 3*3 형태의 2차원 배열 변환
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

# 행과 열 형식 인덱싱해서 원하는 위치의 값 조회. 
print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


* 슬라이싱(slicing)

In [ ]:
# 슬라이싱: 시작:종료 형식으로 범위를 지정하여 추출.

array1 = np.arange(start=1, stop=10)
# 0부터 2번 인덱스까지, 앞에 0,1,2를 잘라냄. 
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

# 끝 인덱스를 생략해서 지정한 위치부터 끝까지 슬라이싱
array5 = array1[3:]
print(array5)

# 모두 생략시 전체 배열 반환.
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# 1차원 배열 후에 3*3 형태의 2차원 배열 변환
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

# 행과 열 범위 지정해서 부분배열 추출. 
print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [ ]:
#행 인덱스 하나만 지정시 해당 행 전체가 1차원 배열로 변환. 
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


* 팬시인덱싱 fancy indexing

In [ ]:
#팬시 인덱싱(Fancy Indexing): 
#리스트나 배열로 인덱스 집합을 지정하여 해당 위치의 데이터 반환.

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
#리스트로 전달헤 특정 열 값을 조회 한번에
array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())

# 여러 행과 열 범위 조합해 부분 배열 추출. 
array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())

# 리스트로 전달시 선택한 행만 새로운 배열로 변환
array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


* 불린 인덱싱 Boolean indexing

In [23]:
# 불린 인덱싱(Boolean Indexing)
# 조건식(예: array > 5)을 넣어 True인 값만 필터링.

array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [ ]:
array1d > 5
#결과적으로 True, False로 보임.

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

# 직접 만든 불린 마스크를 이용해서 원하는 위치의 값만 선택. 

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [ ]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

# 정수 인덱스 배열 사용시 특정 위치 값만 선택됨. 

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬 – sort( )와 argsort( )

* 행렬 정렬

In [27]:
# 정렬:  np.sort() vs ndarray.sort()
# np.sort(): 원본은 그대로 두고 정렬된 복사본 반환.
# array.sort(): 원본 자체를 정렬하고 None 반환.

org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)
# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)
# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)


원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [ ]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc)

#[::-1] 슬라이싱이용시 내림차순으로 정렬됨. 

내림차순으로 정렬: [9 5 3 1]


In [ ]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])
# axis=0은 로우 방향 정렬
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)
# axis=1 컬럼 방향으로 정렬
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


* 정렬 행렬의 인덱스 반환

In [30]:
# argsort(): 정렬된 값의 '원본 인덱스'를 반환. 
# 데이터(이름)와 레이블(성적)이 별도 배열일 때, 성적순으로 이름을 나열하기 위해 필수적으로 사용됩니다.
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [31]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [ ]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])
# 점수를 오름차순으로 정렬시 인덱스 구할 수 있음. 
sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])
# 이름 배열에 적용시, 점수 순서대로 이름이 출력됨.

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 – 행렬 내적과 전치 행렬 구하기

* 행렬 내적(행렬 곱)

In [ ]:
# np.dot(): 행렬 내적(Dot Product). 
#앞 행렬의 열 개수와 뒤 행렬의 행 개수가 같아야 함.

A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
#np.dot으로 두 행렬의 행렬곱을 계산 .
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


* 전치 행렬

In [ ]:
# np.transpose(): 전치 행렬. 행과 열의 위치를 바꿈.
A = np.array([[1, 2],
              [3, 4]])
              
#np.transpose로 행과 열을 서로 바꾼 전치 행렬 시헹
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
