넘파이 ndarray 개요

In [1]:
import numpy as np

In [4]:
#np.array(): 인자를 ndarray로 변환
#.shape : ndarray의 크기를 튜플 형태로 알려줌
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],[2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

# array의 차원을 알려주는 ndarray.ndim
print('array1:{0}차원, array2:{1}차원, array3:{2}차원 '.format(array1.ndim, array2.ndim, array3.ndim))


array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1:1차원, array2:2차원, array3:2차원 


ndarray의 데이터 타입

In [6]:
#dtype으로 데이터 속성을 확인
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

#ndarray 내의 데이터 타입은 동일해야 하므로, 크기가 큰 데이터 타입으로 일괄 적용
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64
['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [7]:
#데이터 타입을 변경하려면? .astype()
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1,array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


ndarray 편리하게 생성하기 - arange, zeros, ones

In [8]:
#arange() - array를 range로 표현
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [9]:
#zeros()-인자 : 튜플 형태의 shape값 -> 반환: 모든 값을 0으로 채운 ndarray
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

#ones()-인자 : 튜플 형태의 shape값 -> 반환 : 모든 값을 1로 채운 ndarray
one_array = np.ones((3,2)) #dtype 인자에 입력하지 않으면 float64가 default
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


ndarray의 차원과 크기를 결정하는 reshape()

In [11]:
#reshape(): 함수 인자 = 원하는 크기, ndarray를 특정 차원 및 크기로 반환
array1 = np.arange(10)
print('array1:\n',array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array4 = array1.reshape(-1,5)
print('array4 shape:', array4.shape)

array5 = array1.reshape(5,-1)
print('array5 shape:', array5.shape)



array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array4 shape: (2, 5)
array5 shape: (5, 2)


In [12]:
#10으로 만들 수 없는 사이즈는 당연히 안 된다
array1.reshape(4,3)


ValueError: cannot reshape array of size 10 into shape (4,3)

In [13]:
#tolist() : ndarray를 list로
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)




array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱

In [14]:
#1. 단일값 추출 in 1차원
array1 = np.arange(1,10)
print('array1:', array1)
value = array1[2]
print('value:', value)
print(type(value)) # 단일 추출값은 더 이상 ndarray가 아님
print('맨 뒤의 값:', array1[-1],'맨 뒤에서 두번째 값:',array1[-2])

# 단일 인덱스를 이용해 데이터 값 수정
array1[0] = 9
array1[8] = 0
print('array1:', array1)

# 단일값 추출 in 다차원
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])



array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
맨 뒤의 값: 9 맨 뒤에서 두번째 값: 8
array1: [9 2 3 4 5 6 7 8 0]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [16]:
#2. 슬라이싱 : 연속한 데이터 추출
array1 = np.arange(1,10)
array3 = array1[0:3]
print(array3)
print(type(array3))

# : 전후로 생략시 처음/끝 지칭
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

#다차원에서의 슬라이싱
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2,0:2]\n', array2d[0:2,0:2])
print('array2d[1:3,0:3]\n', array2d[1:3,0:3])
print('array2d[1:3,:]\n', array2d[1:3,:])
print('array2d[:,:]\n', array2d[:,:])
print('array2d[:2,1:]\n', array2d[:2,1:])
print('array2d[:2,0]\n', array2d[:2,0])

#n차원[] -> (n-1)차원 ndarray 반환
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]
[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [17]:
#3. 팬시 인덱싱 -> 인덱스 집합을 리스트나 ndarray로 입력해 해당 ndarray 반환
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] =>', array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] =>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())


array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


In [19]:
#4. 불린 인덱싱 : 조건문 통해 인덱싱
array1d = np.arange(1,10)
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)

#위 결과와 동일
array1d > 5
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)


array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]
불린 인덱스로 필터링 결과: [6 7 8 9]


행렬의 정렬 - sort()와 argsort()

In [22]:
#np.sort() : 원 행렬은 그대로, 정렬된 행렬을 반환
#ndarray.sort() : 원 행렬 자체를 정렬, 반환값은 None

org_array = np.array([3,1,9,5])
print('원본 행렬:',org_array)
#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:',org_array)

#내림차순으로 정렬하려면? [::-1]
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)

#다차원 행렬의 정렬
array2d = np.array([[8,12], [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n',sort_array2d_axis0)
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n',sort_array2d_axis1)


원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]
내림차순으로 정렬: [9 5 3 1]
로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [23]:
#정렬된 행렬의 인덱스 반환 -> np.argsort()
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

#내림차순으로 정렬 시는? [::-1]
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

#argsort()의 활용 - 두 ndarray 연결
import numpy as np

name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]
성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


선형대수 연산 - 행렬 내적과 전치 행렬

In [24]:
#행렬 내적 구하기 w. np.dot()
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [25]:
#전치 행렬 구하기 w. np.transpose()
A = np.array([[1,2],[3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
