In [11]:
import numpy as np

In [12]:
# 1차원 array 생성
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:',array1.shape)
# 2차원 array(2개 로우, 3개 컬럼) 생성
array2=np.array([[1,2,3],
                 [4,5,6]])
print('array2 type:', type(array2))
print('array2 array 형태:',array2.shape)

# 2차원 array(1개 로우, 3개 컬럼) 생성
array3=np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:',array3.shape)



array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [13]:
#array의 차원 확인  
print('array1: {0}차원,array2:{1}차원,array3:{2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원,array2:2차원,array3:2차원


In [14]:
#같은 타입의 리스트를 ndarray로 변경
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

#서로 다른 타입을 가지는 리스트(int,string형)를 ndarray로 변경
list2=[1,2,'test']
array2=np.array(list2)
print(array2,array2.dtype)

#서로 다른 타입을 가지는 리스트(int,float형)를 ndarray로 변경
list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)


<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64
['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [15]:
#astype 메소드로 ndarray내 데이터값 타입 변경 (int->float,float->int)
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

#astype 메소드로 ndarray내 데이터값 타입 변경 (float->int)
array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2,array_int2.dtype)




[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [16]:
#arange 함수로 ndarray 생성
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

#zero 함수로 2차원 ndarray 생성
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)

#ones 함수로 2차원 ndarray 생성
one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)


[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [17]:
array1=np.arange(10)
print('array1:\n',array1)

#reshape로 2차원 배열로 변환
array2=array1.reshape(2,5)
print('array2:\n',array2)

array3=array1.reshape(5,2)
print('array3:\n',array3)

# 지정된 사이즈로 변경이 불가능할경우
array1.reshape(4,3)


array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


ValueError: cannot reshape array of size 10 into shape (4,3)

In [18]:
array1=np.arange(10)
print('array1:\n',array1)

#reshape(-1,5)의 의미는 5열로 맞추되 나머지는 알아서 처리하라는것
array2=array1.reshape(-1,5)
print('array2:\n',array2)

# reshape(5,-1)은 5행으로 맞추되 나머지는 알아서 처리하라는것, -1을 쓰는 이유는 데이터의 개수가 바뀌어도 코드 수정안해도되서 사용
array3=array1.reshape(5,-1)
print('array3:\n',array3)

# -1인자를 사용한 reshape에서도 호환될수없는 형태는 변환 불가능
array4=array1.reshape(-1,4)



array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


ValueError: cannot reshape array of size 10 into shape (4)

In [19]:
array1=np.arange(8)
array3d=array1.reshape(2,2,2)
print('array3d:\n',array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(2,4)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0, 1, 2, 3], [4, 5, 6, 7]]
array6 shape: (2, 4)


In [20]:
#단일값 추출
#1부터 9까지 1차원 ndarray 생성
array1=np.arange(1,10)
print('array1:',array1)
#인덱싱으로 3번째 Index 위치의 데이터값 추출
value=array1[2]
print('value:',value)
print(type(value))

#슬라이싱으로 맨뒤의 데이터값 추출
print('맨 뒤의 데이터값:',array1[-1],'맨 뒤에서 두번째 값:',array1[-2])

#단일 인덱스로 ndarray내 데이터값 수정
array1[0]=9
array1[8]=0
print('array1:',array1)


array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
맨 뒤의 데이터값: 9 맨 뒤에서 두번째 값: 8
array1: [9 2 3 4 5 6 7 8 0]


In [21]:
#다차원 ndarray에서 단일값 추출
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:',array2d[0,0])
print('(row=0,col=1) index 가리키는 값:',array2d[0,1])
print('(row=1,col=0) index 가리키는 값:',array2d[1,0])
print('(row=2,col=2) index 가리키는 값:',array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


In [22]:
#슬라이싱
array1=np.arange(1,10)
#0번째부터 2번째 인덱스까지 반환
array3=array1[0:3]
print(array3)
print(type(array3))

#슬라이싱의 시작,종료 인덱스를 생략하면 맨처음,맨마지막 인덱스로 간주
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [23]:
#2차원 ndarray 슬라이싱
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2,0:2] \n', array2d[0:2,0:2])
print('array2d[1:3,0:3] \n', array2d[1:3,0:3])
print('array2d[1:3,:] \n', array2d[1:3,:])
print('array2d[:,:] \n', array2d[:,:])
print('array2d[:2,1:] \n', array2d[:2,1:])
print('array2d[:2,0] \n', array2d[:2,0])



array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2] 
 [[1 2]
 [4 5]]
array2d[1:3,0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:] 
 [[4 5 6]
 [7 8 9]]
array2d[:,:] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:] 
 [[2 3]
 [5 6]]
array2d[:2,0] 
 [1 4]


In [24]:
# n차원 ndarray에서 뒤에오는 인덱스 없애면 n-1차원 ndarray 반환
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:',array2d[0].shape,'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [25]:
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)

#fancy indexing
#로우축에 [0,1] 인덱싱, 컬럼축에 2 인덱싱
array3=array2d[[0,1],2]
print('array2d[[0,1],2] =>',array3.tolist())
#로우축은 위와 동일, 컬럼축을 0~1번째까지 인덱싱
array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2] =>',array4.tolist())
#0번행,1번행 추출
array5=array2d[[0,1]]
print('array2d[[0,1]] =>',array5.tolist())


array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


In [26]:
#불린 인덱싱(조건 필터링과 검색 동시에 가능)
array1d=np.arange(1,10)

#[]안에 array1d>5 불린 인덱싱 적용
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:',array3)

#조건 필터링을 통한 True/False 배열 반환
print(array1d>5)

#불린 인덱스로 배열 반환
boolean_indexes=np.array([False,False,False,False,False,True,True,True,True])
array3=array1d[boolean_indexes]
print('불린 인덱싱로 필터링 결과:',array3)

#일반 인덱스로 필터링 
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과:',array4)




array1d>5 불린 인덱싱 결과 값: [6 7 8 9]
[False False False False False  True  True  True  True]
불린 인덱싱로 필터링 결과: [6 7 8 9]
일반 인덱스로 필터링 결과: [6 7 8 9]


In [29]:
#행렬 정렬
#np.sort()와 ndarray.sort()의 차이
org_array=np.array([3,1,9,5])

#np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort()로 호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort()호출 후 원본 행렬:',org_array)

#ndarray.sort()로 정렬
sort_array2=org_array.sort()
print('ndarray.sort() 호출 후 반환된 정렬 행렬:',sort_array2)
print('ndarray.sort()호출 후 원본 행렬:',org_array)

#차이는 np.sort는 정렬된 행렬을 반환하고 원본행렬은 변경하지않고 ndarray.sort는 반환값은 없지만 원본행렬은 변경됨

#내림차순으로 정렬하기 위해서는 [::-1]을 사용
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)



np.sort()로 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort()호출 후 원본 행렬: [3 1 9 5]
ndarray.sort() 호출 후 반환된 정렬 행렬: None
ndarray.sort()호출 후 원본 행렬: [1 3 5 9]
내림차순으로 정렬: [9 5 3 1]


In [4]:
#다차원 행렬에서의 정렬
#axis 축 값 설정을 통해 정렬
array2d=np.array([[8,12],
                 [7,1]])
#로우방향으로 정렬
sort_array2d_axis0=np.sort(array2d,axis=0)
print('로우 방향으로 정렬: \n', sort_array2d_axis0)

#컬럼방향으로 정렬
sort_array2d_axis1=np.sort(array2d,axis=1)
print('컬럼 방향으로 정렬: \n', sort_array2d_axis1)



로우 방향으로 정렬: 
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬: 
 [[ 8 12]
 [ 1  7]]


In [ ]:
#정렬 후 원본행렬의 인덱스 반환
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

#내림 차순에 대한 argsort
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)




<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [6]:
#argsort 사용후 반환된 인덱스를 팬시인덱스로 적용해 데이터 추출

name_array=np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [10]:
#행렬 내적
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8],[9,10],[11,12]])
dot_product=np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)

#전치 행렬(transpose)
A=np.array([[1,2],[3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n',transpose_mat)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]
A의 전치 행렬:
 [[1 3]
 [2 4]]
