In [1]:
# 붓꽃 품종 예측하기
# 붓꽃 데이터 세트로 붓꽃의 품종 분류
# 붓꽃 데이터 세트 - 꽃잎의 길이와 너비, 꽃받침의 길이와 너비 피처를 기반으로

In [3]:
# 분류 = 대표적인 지도학습 방법의 하나
# 지도학습 = 주어진데이터(다양한 피처와 분류결정값인 레이블데이터)로 모델을 학습한 뒤, 별도의 테스트 데이터 셋에서 레이블 예측

In [4]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [5]:
import pandas as pd

# 붓꽃 데이터 세트를 로딩
iris = load_iris()

# iris.data는 iris 데이터 세트에서 피처(feature)만으로 된 데이터를 numpy로 가지고 있습니다.
iris_data = iris.data

# iris.target은 붓꽃 데이터 세트에서 레이블(결정값) 데이터를 numpy로 가지고 있습니다.
iris_label = iris.target
print('iris target값', iris_label)
print('iris target명', iris.target_names)

# 붓꽃 데이터 세트를 자세히 보기 위해 dataframe으로 변환합니다.
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

iris target값 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명 ['setosa' 'versicolor' 'virginica']


,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0


In [7]:
# feature 에는 sepal length 부터 petal width가 있음
# label(결정값)은 0,1,2, 세가지 값으로 되어 있으며 0이 setosa 품종, 1이 versicolor 품종, 2가 virginica 품종

In [8]:
# trian_test_split()을 이용하여 학습데이터와 테스트 데이터를 분리
# test_size 파라미터 입력값을 0.2로 하면 전체중 테스트데이터가 20%, 학습데이터가 80%로 분할됨
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

In [19]:
# Decisiontreeclassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

# 학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [21]:
# 학습이 완료된 Decisiontreeclassifier 객체에서 테스트 데이터 세트로 예측 수행
pred = dt_clf.predict(X_test)

In [23]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,pred))

0.9333333333333333


In [25]:
# 1. 데이터셋 분리: 데이터를 학습데이터와 테스트 데이터로 분리
# 2. 모델학습: 학습 데이터를 기반으로 ML 알고리즘을 적용해 모델을 학습시킨다
# 3. 예측수행: 학습된 ML 모델을 이용해 테스트 데이터의 분류(붓꽃 종류)를 예측
# 4. 평가: 이렇게 예측된 결과값과 테스트 데이터의 실제 결과값을 비교해 ML 모델 성능을 평가

In [27]:
from sklearn.datasets import load_iris

iris_data = load_iris()
type(iris_data)

sklearn.utils._bunch.Bunch

In [29]:
keys = iris_data.keys()
keys

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [31]:
iris_data.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 

In [35]:
iris_data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [39]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data, train_label)

# 학습 데이터 셋으로 예측 수행
pred = dt_clf.predict(train_data)
accuracy_score(train_label, pred)

1.0

In [41]:
# 정확도가 100% 임 => 이미 학습한 학습데이터 셋을 기반으로 예측했기 때문
# trian_test_split()을 통해 데이터셋을 분리해야함

In [45]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

iris_data = load_iris()
dt_clf = DecisionTreeClassifier()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)

In [47]:
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
accuracy_score(y_test, pred)

0.9555555555555556

In [49]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

# 5개의 폴드 세트로 분리하는 kfold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy = []
print('붓꽃 데이터셋크기', features.shape[0])

붓꽃 데이터셋크기 150


In [55]:
# 붓꽃 데이터셋 크기가 150이므로 5개로 나누면 학습용데이터셋은 120개, 검증 데이터셋은 30개가 됨

n_iter = 0
# kfold 객체의 split()을 호출하면 폴드별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index, in kfold.split(features):
    # kfold.split()로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    # 학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    # 반복 시마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print(f'{n_iter} 교차검증 정확도: {accuracy}, 학습데이터크기: {train_size}, 검증데이터크기: {test_size}, 검증세트 인덱스: {test_index}')
    cv_accuracy.append(accuracy)

# 개별 iteration별 정확도를 합하여 평균 정확도 계산
print('평균 검증 정확도:' , np.mean(cv_accuracy))

1 교차검증 정확도: 1.0, 학습데이터크기: 120, 검증데이터크기: 30, 검증세트 인덱스: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
2 교차검증 정확도: 0.9667, 학습데이터크기: 120, 검증데이터크기: 30, 검증세트 인덱스: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]
3 교차검증 정확도: 0.8667, 학습데이터크기: 120, 검증데이터크기: 30, 검증세트 인덱스: [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]
4 교차검증 정확도: 0.9333, 학습데이터크기: 120, 검증데이터크기: 30, 검증세트 인덱스: [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
5 교차검증 정확도: 0.7333, 학습데이터크기: 120, 검증데이터크기: 30, 검증세트 인덱스: [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
평균 검증 정확도: 0.9


In [57]:
# stratified k fold : 불균형한 분포도를 가진 데이터 문제를 해결해줌
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

label
0    50
1    50
2    50
Name: count, dtype: int64

In [59]:
kfold = KFold(n_splits=3)
n_iter=0
for train_index, test_index, in kfold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(f'## 교차검증 : {n_iter}')
    print('학습레이블 데이터분포: \n', label_train.value_counts())
    print('검증레이블 데이터분포: \n', label_test.value_counts())

## 교차검증 : 1
학습레이블 데이터분포: 
 label
1    50
2    50
Name: count, dtype: int64
검증레이블 데이터분포: 
 label
0    50
Name: count, dtype: int64
## 교차검증 : 2
학습레이블 데이터분포: 
 label
0    50
2    50
Name: count, dtype: int64
검증레이블 데이터분포: 
 label
1    50
Name: count, dtype: int64
## 교차검증 : 3
학습레이블 데이터분포: 
 label
0    50
1    50
Name: count, dtype: int64
검증레이블 데이터분포: 
 label
2    50
Name: count, dtype: int64


In [65]:
## 교차검증 1번째의 경우에 학습레이블엔 1,2 밖에 없고 검증레이블에 0 밖에 없으므로 절대 0을 예측하지 못해 예측 정확도는 0이 될 수 밖에 없음
# stratifiedkfold를 통해 분활된 레이블 데이터세트가 전체레이블 값의 분포도를 반영하도록
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter = 0

for train_index, test_index, in skf.split(iris_df,iris_df['label']):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(f'## 교차검증 : {n_iter}')
    print('학습레이블 데이터분포: \n', label_train.value_counts())
    print('검증레이블 데이터분포: \n', label_test.value_counts())

## 교차검증 : 1
학습레이블 데이터분포: 
 label
2    34
0    33
1    33
Name: count, dtype: int64
검증레이블 데이터분포: 
 label
0    17
1    17
2    16
Name: count, dtype: int64
## 교차검증 : 2
학습레이블 데이터분포: 
 label
1    34
0    33
2    33
Name: count, dtype: int64
검증레이블 데이터분포: 
 label
0    17
2    17
1    16
Name: count, dtype: int64
## 교차검증 : 3
학습레이블 데이터분포: 
 label
0    34
1    33
2    33
Name: count, dtype: int64
검증레이블 데이터분포: 
 label
1    17
2    17
0    16
Name: count, dtype: int64


In [70]:
dt_clf = DecisionTreeClassifier(random_state=156)

skf = StratifiedKFold(n_splits=3)
n_iter = 0
cv_accuracy = []

# stratifiedkfold 의 split() 호출시 반드시 레이블 데이터셋도 추가 입력필요
for train_index, test_index, in skf.split(features, label):
    # split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    # 학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    # 반복 시마다 정확도 측정
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print(f'{n_iter} 교차검증 정확도: {accuracy}, 학습데이터크기: {train_size}, 검증데이터크기: {test_size}, 검증세트 인덱스: {test_index}')
    cv_accuracy.append(accuracy)

# 개별 iteration별 정확도를 합하여 평균 정확도 계산
print('교차검증별 정확도: ', np.round(cv_accuracy,4))
print('평균 검증 정확도: ' , np.mean(cv_accuracy))

1 교차검증 정확도: 0.98, 학습데이터크기: 100, 검증데이터크기: 50, 검증세트 인덱스: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]
2 교차검증 정확도: 0.94, 학습데이터크기: 100, 검증데이터크기: 50, 검증세트 인덱스: [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]
3 교차검증 정확도: 0.98, 학습데이터크기: 100, 검증데이터크기: 50, 검증세트 인덱스: [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]
교차검증별 정확도:  [0.98 0.94 0.98]
평균 검증 정확도:  0.9666666666666667


In [72]:
# cross_val_score(): 이러한 교차검증을 간편하게 수행하는 API 제공
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target

# 성능지표는 정확도(accuracy), 교차검증세트는 3개
scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print('교차검증별 정확도: ', np.round(scores,4))
print('평균 검증 정확도: ' , np.round(np.mean(scores),4))

교차검증별 정확도:  [0.98 0.94 0.98]
평균 검증 정확도:  0.9667


In [74]:
# GridSearchCV

from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import GridSearchCV

# 데이터를 로딩하고 학습 데이터와 테스트 데이터 분리
iris_data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)
dtree = DecisionTreeClassifier()

### 파라미터를 딕셔너리 형태로 설정
parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [76]:
import pandas as pd

# param_grid의 하이퍼 파라미터를 3개의 trian, test set fold로 나누어 테스트 수행 설정
### refit=True가 default임. true이면 가장 좋은 파라미터 설정으로 재학습시킴
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3,refit=True)

# 붓꽃 학습데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가
grid_dtree.fit(X_train, y_train)

# gridsearchcv 결과를 추출해 dataframe으로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

,params,mean_test_score,rank_test_score,split0_test_score,split1_test_score,split2_test_score
0,"{'max_depth': 1, 'min_samples_split': 2}",0.700000,5,0.700,0.7,0.70
1,"{'max_depth': 1, 'min_samples_split': 3}",0.700000,5,0.700,0.7,0.70
2,"{'max_depth': 2, 'min_samples_split': 2}",0.958333,3,0.925,1.0,0.95
3,"{'max_depth': 2, 'min_samples_split': 3}",0.958333,3,0.925,1.0,0.95
4,"{'max_depth': 3, 'min_samples_split': 2}",0.975000,1,0.975,1.0,0.95
5,"{'max_depth': 3, 'min_samples_split': 3}",0.975000,1,0.975,1.0,0.95


In [78]:
# rank_test_score 값이 1인게 평가한 예측 성능이 1위라는 뜻
# {'max_depth': 3, 'min_samples_split': 2}일때 예측 성능이 1위

In [80]:
print('최적 파라미터' , grid_dtree.best_params_)
print('최고 정확도', grid_dtree.best_score_)

최적 파라미터 {'max_depth': 3, 'min_samples_split': 2}
최고 정확도 0.975


In [82]:
# refit=true 이면 gridsearchcv가 최적성능을 나타내는 하이퍼파라미터로 estimaor를 학습해 best_estimator_로 저장
# gridsearchcv의 refit으로 이미 학습된 estimator 반환
estimator = grid_dtree.best_estimator_

# gridsearchcv의 best_estimator_는 이미 최적학습이 됐으므로 별도 학습이 필요없음
pred = estimator.predict(X_test)
print('테스트데이터세트 정확도', accuracy_score(y_test,pred))

테스트데이터세트 정확도 0.9666666666666667


In [90]:
# 레이블 인코딩: 상품데이터가 tv,컴퓨터,냉장고 라면 tv=1,냉장고=2,컴퓨터=3 등 숫자형 값으로 변환
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','믹서','믹서']

# labelencoder를 객체로 생성한 후 fit()과 transform()으로 레이블 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값', labels)

인코딩 변환값 [0 1 4 5 3 2 2]


In [92]:
print('인코딩 클래스', encoder.classes_)

인코딩 클래스 ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [94]:
# tv는 0, 냉장고는 1 ...

In [96]:
# 회귀같이 특정 알고리즘에서는 가중치가 더 부여되거나 더 중요하게 인식할 가능성이 있으므로 레이블 인코딩 적용x
# 트리계열은 상관없음

In [98]:
# 이러한 문제를 해결하기 위해 원핫인코딩: 피처 값의 유형에 따라 새로운 피처를 추가해 고유값에 해당하는 칼럼에만 1, 나머지는 0
# 여러개의 속성중 단 한개의 속성만 1로 표시

In [100]:
# ONE_HOT_ENCODING
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','믹서','믹서']

# 2차원 ndarray로 변환합니다.
items = np.array(items).reshape(-1,1)

# 원-핫 인코딩을 적용합니다.
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

# OneHotEncoder로 변환한 결과는 희소행렬이므로 toarray()를 이용해 밀집행렬로 변환
print('원핫인코딩데이터')
print(oh_labels.toarray())
print('원핫 인코딩 데이터 차원')
print(oh_labels.shape)

원핫인코딩데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원핫 인코딩 데이터 차원
(7, 6)


In [102]:
# 원핫인코딩을 더쉽게 지원하는 api => get_dummies()를 이용

import pandas as pd

df = pd.DataFrame({'item': ['TV','냉장고','전자레인지','컴퓨터','선풍기','믹서','믹서']})
pd.get_dummies(df)

,item_TV,item_냉장고,item_믹서,item_선풍기,item_전자레인지,item_컴퓨터
0,True,False,False,False,False,False
1,False,True,False,False,False,False
2,False,False,False,False,True,False
3,False,False,False,False,False,True
4,False,False,False,True,False,False
5,False,False,True,False,False,False
6,False,False,True,False,False,False


In [104]:
from sklearn.datasets import load_iris
import pandas as pd
# 붓꽃 데이터 세트를 로딩하고 Dataframe으로 변환합니다
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature 평균', iris_df.mean())
print('feature 분산', iris_df.var())

feature 평균 sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
feature 분산 sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [108]:
from sklearn.preprocessing import StandardScaler

# StandardSclaer 객체 생성
scaler = StandardScaler()
# Standardscaler로 데이터 셋 변환. fit()와 transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform() 시 스케일 변환된 데이터 세트가 numpy ndarray로 반환돼 이를 dataframe으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 평균', iris_df_scaled.mean())
print('feature 분산', iris_df_scaled.var()) # 평균은 0에 가깝게, 분산은 1에 가깝게

feature 평균 sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
feature 분산 sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [114]:
# minmaxscaler : 데이터값을 0과 1 사이의 범위 값으로
from sklearn.preprocessing import MinMaxScaler

# minmaxscaler 객체 생성
scaler = MinMaxScaler()
# minmaxscaler로 데이터셋 변환. fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform() 시 스케일 변환된 데이터세트가 numpy ndarray로 반환돼 이를 dataframe으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 최소', iris_df_scaled.min())
print('feature 최대', iris_df_scaled.max())

feature 최소 sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
feature 최대 sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


In [118]:
# 테스트 데이터에 scale 변환을 할 때는 반드시 fit() 호출을 하지 않고 transform()만으로 변환해야함