### 데이터 인코딩

* 레이블 인코딩(Label encoding)

In [1]:
# LabelEncoder를 불러온다.
from sklearn.preprocessing import LabelEncoder

# 인코딩할 문자열 데이터를 리스트로 생성한다.
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# LabelEncoder 객체를 생성한다.
encoder = LabelEncoder()

# 문자열 데이터를 기준으로 인코딩 규칙을 학습한다.
encoder.fit(items)

# 학습된 규칙에 따라 문자열 데이터를 숫자 레이블로 변환한다.
labels = encoder.transform(items)

# 인코딩된 결과를 출력한다.
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [2]:
# LabelEncoder가 학습한 클래스(원본 문자열 값)를 출력한다.
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [3]:
# 숫자 레이블을 다시 원래 문자열 값으로 복원하여 출력한다.
print('디코딩 원본 값:', encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))

디코딩 원본 값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


* 원-핫 인코딩(One-Hot encoding)

In [4]:
# OneHotEncoder와 numpy를 불러온다.
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# 원-핫 인코딩할 문자열 데이터를 리스트로 생성한다.
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# OneHotEncoder는 2차원 배열 입력을 받기 때문에 reshape(-1, 1)로 형태를 바꾼다.
items = np.array(items).reshape(-1, 1)

# OneHotEncoder 객체를 생성한다.
oh_encoder = OneHotEncoder()

# 데이터에 대해 인코딩 기준을 학습한다.
oh_encoder.fit(items)

# 학습된 기준에 따라 원-핫 인코딩을 수행한다.
oh_labels = oh_encoder.transform(items)

# 원-핫 인코딩 결과는 희소행렬 형태이므로 toarray()로 일반 배열로 변환하여 출력한다.
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())

# 인코딩된 데이터의 차원을 출력한다.
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [5]:
# pandas를 불러온다.
import pandas as pd

# 문자열 데이터를 DataFrame으로 생성한다.
df = pd.DataFrame({'item': ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})

# pandas의 get_dummies()를 이용하여 원-핫 인코딩을 수행한다.
pd.get_dummies(df)

,item_TV,item_냉장고,item_믹서,item_선풍기,item_전자레인지,item_컴퓨터
0,True,False,False,False,False,False
1,False,True,False,False,False,False
2,False,False,False,False,True,False
3,False,False,False,False,False,True
4,False,False,False,True,False,False
5,False,False,False,True,False,False
6,False,False,True,False,False,False
7,False,False,True,False,False,False


### 피처 스케일링과 정규화

* StandardScaler

In [6]:
# 붓꽃 데이터 로드 함수와 pandas를 불러온다.
from sklearn.datasets import load_iris
import pandas as pd

# 붓꽃 데이터 세트를 불러온다.
iris = load_iris()
iris_data = iris.data

# 붓꽃 데이터를 DataFrame 형태로 변환한다.
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

# 스케일링 전 각 feature의 평균값을 출력한다.
print('feature 들의 평균 값')
print(iris_df.mean())

# 스케일링 전 각 feature의 분산값을 출력한다.
print('\nfeature 들의 분산 값')
print(iris_df.var())

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [7]:
# StandardScaler를 불러온다.
from sklearn.preprocessing import StandardScaler

# StandardScaler 객체를 생성한다.
scaler = StandardScaler()

# 데이터의 평균과 분산을 기준으로 스케일링 규칙을 학습한다.
scaler.fit(iris_df)

# 학습된 규칙을 이용해 데이터를 표준화한다.
iris_scaled = scaler.transform(iris_df)

# 변환된 결과는 numpy 배열이므로 다시 DataFrame으로 변환한다.
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

# 스케일링 후 각 feature의 평균값을 출력한다.
print('feature 들의 평균 값')
print(iris_df_scaled.mean())

# 스케일링 후 각 feature의 분산값을 출력한다.
print('\nfeature 들의 분산 값')
print(iris_df_scaled.var())

feature 들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


* MinMaxScaler

In [8]:
# MinMaxScaler를 불러온다.
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler 객체를 생성한다.
scaler = MinMaxScaler()

# 각 feature의 최솟값과 최댓값을 기준으로 스케일링 규칙을 학습한다.
scaler.fit(iris_df)

# 학습된 규칙에 따라 데이터를 0~1 범위로 변환한다.
iris_scaled = scaler.transform(iris_df)

# 변환된 결과를 DataFrame으로 다시 만든다.
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

# 스케일링 후 각 feature의 최솟값을 출력한다.
print('feature들의 최솟값')
print(iris_df_scaled.min())

# 스케일링 후 각 feature의 최댓값을 출력한다.
print('\nfeature들의 최댓값')
print(iris_df_scaled.max())

feature들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


* Scaler를 이용하여 학습 데이터와 테스트 데이터에 fit(), transform(), fit_transform() 적용 시 유의사항.

In [9]:
# MinMaxScaler와 numpy를 불러온다.
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# 학습 데이터와 테스트 데이터를 예시로 생성한다.
# train_array는 0~10, test_array는 0~5 값을 가진다.
# reshape(-1, 1)을 사용하여 2차원 배열 형태로 변환한다.
train_array = np.arange(0, 11).reshape(-1, 1)
test_array = np.arange(0, 6).reshape(-1, 1)

In [10]:
# MinMaxScaler 객체를 생성한다.
scaler = MinMaxScaler()

# 학습 데이터(train_array)를 기준으로 최솟값과 최댓값을 학습한다.
scaler.fit(train_array)

# 학습 데이터에 대해 스케일 변환을 수행한다.
train_scaled = scaler.transform(train_array)

# 원본 학습 데이터와 스케일링된 데이터를 출력한다.
print('원본 train_array 데이터:', np.round(train_array.reshape(-1), 2))
print('Scale된 train_array 데이터:', np.round(train_scaled.reshape(-1), 2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [11]:
# test_array에 대해 다시 fit()을 수행하면,
# 학습 데이터 기준이 아니라 테스트 데이터 기준으로 최솟값/최댓값이 새로 설정된다.
scaler.fit(test_array)

# 테스트 데이터 기준으로 다시 스케일링을 수행한다.
test_scaled = scaler.transform(test_array)

# 원본 테스트 데이터와 스케일링된 데이터를 출력한다.
print('원본 test_array 데이터:', np.round(test_array.reshape(-1), 2))
print('Scale된 test_array 데이터:', np.round(test_scaled.reshape(-1), 2))

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.2 0.4 0.6 0.8 1. ]


In [12]:
# MinMaxScaler 객체를 다시 생성한다.
scaler = MinMaxScaler()

# 학습 데이터로만 fit()을 수행한다.
scaler.fit(train_array)

# 학습 데이터를 스케일링한다.
train_scaled = scaler.transform(train_array)

# 학습 데이터 스케일링 결과를 출력한다.
print('원본 train_array 데이터:', np.round(train_array.reshape(-1), 2))
print('Scale된 train_array 데이터:', np.round(train_scaled.reshape(-1), 2))

# 테스트 데이터는 절대로 다시 fit()하지 않고, 학습 데이터 기준으로 transform()만 수행해야 한다.
test_scaled = scaler.transform(test_array)

# 테스트 데이터 스케일링 결과를 출력한다.
print('\n원본 test_array 데이터:', np.round(test_array.reshape(-1), 2))
print('Scale된 test_array 데이터:', np.round(test_scaled.reshape(-1), 2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5]
