In [51]:
import sklearn
print(sklearn.__version__)

1.8.0


In [52]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

iris = load_iris()

# data와 target 등의 feature로 구성되어 있다.
iris_data = iris['data']

iris_label = iris['target']

print('iris target names:', iris['target_names'])
print('iris target 값:', iris_label)

iris_df = pd.DataFrame(data=iris_data, columns=iris['feature_names'])
iris_df['label'] = iris['target']
#feature names와 target names 가 별도인가?
print(iris['target_names'])
print(iris['feature_names'])
iris_df.head(5)


iris target names: ['setosa' 'versicolor' 'virginica']
iris target 값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [53]:
train_input, test_input, train_target, test_target = train_test_split(iris_data, iris_label, test_size=0.2, random_state=42)

In [54]:
dt_clf = DecisionTreeClassifier(random_state=42)

dt_clf.fit(train_input, train_target)


,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.",'gini'
,"splitter splitter: {""best"", ""random""}, default=""best""The strategy used to choose the split at each node. Supportedstrategies are ""best"" to choose the best split and ""random"" to choosethe best random split.",'best'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: int, float or {""sqrt"", ""log2""}, default=NoneThe number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... note:: The search for a split does not stop until at least one valid partition of the node samples is found, even if it requires to effectively inspect more than ``max_features`` features.",None
,"random_state random_state: int, RandomState instance or None, default=NoneControls the randomness of the estimator. The features are alwaysrandomly permuted at each split, even if ``splitter`` is set to``""best""``. When ``max_features < n_features``, the algorithm willselect ``max_features`` at random at each split before finding the bestsplit among them. But the best found split may vary across differentruns, even if ``max_features=n_features``. That is the case, if theimprovement of the criterion is identical for several splits and onesplit has to be selected at random. To obtain a deterministic behaviourduring fitting, ``random_state`` has to be fixed to an integer.See :term:`Glossary ` for details.",42
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow a tree with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current

In [55]:
pred = dt_clf.predict(test_input)
pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [56]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(test_target, pred)))
# 이 중괄호는 자리 표시자라는 기능을 한다. 
# 처음의 0은 인덱스로서, .format() 에 들어온 첫 번째 인자(즉, 여기서는 accuracy_score)를 의미한다.
# 구분자 :은 이제부터 이 안에 들어오는 데이터를 어떻게 보여줄지 형식을 지정한다.
# 정밀도 .4 는 소수점 아래 4자리까지 표시
# 타입 f는 부동 소수점(float) 형식으로 출력하라는 명이다.

예측 정확도: 1.0000


In [57]:
# 학습 데이터와 테스트 데이터를 분리 -> fit -> predict -> evaluation
# 03 사이킷런의 기반 프레임워크 익히기

In [58]:
# 교차 검증
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris['data']
label = iris['target']
dt_clf = DecisionTreeClassifier(random_state=42)

kfold = KFold(n_splits=5)
cv_accuracy = []
print(features)
print('붓꽃 데이터 세트 크기:', len(features))
# features.shape[0] 으로 행의 개수를 확인할 셈이라면, 그냥 len(features)를 써도 된다.


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [59]:
n_iter = 0

for train_index, test_index in kfold.split(features):
    train_input, test_input = features[train_index], features[test_index]
    train_target, test_target = label[train_index], label[test_index]
    dt_clf.fit(train_input, train_target)
    pred = dt_clf.predict(test_input)
    n_iter += 1
    accuracy = np.round(accuracy_score(test_target, pred), 4)
    train_size = train_input.shape[0]
    test_size = test_input.shape[0]
    print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'
          .format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)

print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))
# for + format.. 코드를 작성하는 다양한 기법이 복합적으로 있다. 온전히 이해하기 보다는 여기서는 CV의 작동 원리만 파악하는 정도로.


#1 교차 검증 정확도 :1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 :1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도 :0.8333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도 :0.9333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#4 검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도 :0.8, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#5 검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.91332


In [60]:
iris_df = pd.DataFrame(data=iris['data'], columns=iris['feature_names'])
iris_df['label'] = iris['target']
iris_df['label'].value_counts()

label
0    50
1    50
2    50
Name: count, dtype: int64

In [61]:
kfold = KFold(n_splits=3)
n_iter =0
for train_index, test_index in kfold.split(iris_df):
    n_iter += 1
    label_train= iris_df['label'].iloc[train_index]
    label_test= iris_df['label'].iloc[test_index]
    print('## 교차 검증: {0}' .format(n_iter))
    print('학습 레이블 분포:', label_train.value_counts())
    print('테스트 레이블 분포:', label_test.value_counts())

## 교차 검증: 1
학습 레이블 분포: label
1    50
2    50
Name: count, dtype: int64
테스트 레이블 분포: label
0    50
Name: count, dtype: int64
## 교차 검증: 2
학습 레이블 분포: label
0    50
2    50
Name: count, dtype: int64
테스트 레이블 분포: label
1    50
Name: count, dtype: int64
## 교차 검증: 3
학습 레이블 분포: label
0    50
1    50
Name: count, dtype: int64
테스트 레이블 분포: label
2    50
Name: count, dtype: int64


In [62]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter=0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter += 1
    label_train= iris_df['label'].iloc[train_index]
    label_test= iris_df['label'].iloc[test_index]
    print('## 교차 검증: {0}' .format(n_iter))
    print('학습 레이블 분포:', label_train.value_counts())
    print('테스트 레이블 분포:', label_test.value_counts())


## 교차 검증: 1
학습 레이블 분포: label
2    34
0    33
1    33
Name: count, dtype: int64
테스트 레이블 분포: label
0    17
1    17
2    16
Name: count, dtype: int64
## 교차 검증: 2
학습 레이블 분포: label
1    34
0    33
2    33
Name: count, dtype: int64
테스트 레이블 분포: label
0    17
2    17
1    16
Name: count, dtype: int64
## 교차 검증: 3
학습 레이블 분포: label
0    34
1    33
2    33
Name: count, dtype: int64
테스트 레이블 분포: label
1    17
2    17
0    16
Name: count, dtype: int64


In [63]:
dt_clf = DecisionTreeClassifier(random_state=42)
skfold = StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

# StratifiedKFold의 split( ) 호출시 반드시 레이블 데이터 세트도 추가 입력 필요
for train_index, test_index in skfold.split(features, label):

# split( )으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    train_input, test_input = features[train_index], features[test_index]
    train_target, test_target = label[train_index], label[test_index]

#학습 및 예측
    dt_clf.fit(train_input, train_target)
    pred = dt_clf.predict(test_input)

# 반복 시마다 정확도 측정
    n_iter += 1
    accuracy = np.round(accuracy_score(test_target, pred), 4)
    train_size = train_input.shape[0]
    test_size = test_input.shape[0]

print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'
.format(n_iter, accuracy, train_size, test_size))


#3 교차 검증 정확도 :0.96, 학습 데이터 크기: 100, 검증 데이터 크기: 50


In [64]:
from sklearn.model_selection import cross_val_score, cross_validate

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=42)

data = iris_data['data']
label = iris_data['target']

scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print(scores)
print(np.mean(scores))

[0.98 0.94 0.96]
0.96


In [65]:
# p.111 GridSearchCV
grid_parameters = {'max_depth': [1, 2, 3],
                   'min_sample_split': [2, 3]
                   }

In [66]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

iris_data = load_iris()
train_input, test_input, train_target, test_target = train_test_split(iris_data['data'], iris_data['target'], test_size=0.2, random_state=121)

In [67]:
dtree = DecisionTreeClassifier()

parameters = {'max_depth':[1, 2, 3], 'min_samples_split': [2, 3]}

In [68]:
import pandas as pd
from sklearn.model_selection import GridSearchCV

grid_tree = GridSearchCV(estimator=dtree, param_grid=parameters, cv=3, n_jobs=-1, refit=True)

In [69]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

train_array = np.arange(0, 11).reshape(-1, 1)
test_array = np.arange(0, 6).reshape(-1, 1)

In [70]:
scaler = MinMaxScaler()

scaler.fit(train_array)
# train_array의 특성을 가지고 scaler을 학습시킨다. 
# scaler의 프레임이 맞춰지는 순간이다.

train_scaled = scaler.transform(train_array)
# 학습시킨 scaler를 이제 활용하는 단계다.
# 새로운 객체 train_scaled 를 transform으로 바꿔서 새롭게 설정한다.

print('원본 train_array data:', np.round(train_array.reshape(-1), 2))
print('Scale된 train_array data:', np.round(train_scaled.reshape(-1), 2))

# round의 2번째 매개변수는 삭제시킬 자릿수를 설정한다. 그러므로 2번째 자리에서
# 삭제시키고 1번째까지 출력된다.
# fit 하고 transform 까지는 2차원만 가능하므로, 결과를 출력할 때는 1차원으로


원본 train_array data: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array data: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [71]:
scaler.fit(test_array)

test_scaled = scaler.transform(test_array)

print('원본 test_array data:', np.round(test_array.reshape(-1), 2))
print('Scale된 test_array data:', np.round(test_scaled.reshape(-1), 2))

# test_array에 scale 변환할 때는 fit() 을 절대 쓰지 않고, transform() 만으로 
# 변환. 그러므로 fit_transform()은 학습 데이터에만 사용하고, 테스트 데이터에는
# 사용하지 않는다.



원본 test_array data: [0 1 2 3 4 5]
Scale된 test_array data: [0.  0.2 0.4 0.6 0.8 1. ]


In [72]:
grid_dtree = GridSearchCV(dtree,                  # 모델 설정
                          param_grid=parameters,  # 탐색할 조합을 딕셔너리로 제공
                          cv=3,                   # 몇 개의 폴드로 나눌지
                          refit=True)             # 최적 파라미터로 재학습 여부

In [73]:
grid_dtree.fit(train_input, train_target)  # 학습 데이터를 사용해서 학습시킨다.

grid_dtree.best_params_    # 최적 하이퍼파라미터
grid_dtree.best_estimator_ # 바로 사용가능한 모델

,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.",'gini'
,"splitter splitter: {""best"", ""random""}, default=""best""The strategy used to choose the split at each node. Supportedstrategies are ""best"" to choose the best split and ""random"" to choosethe best random split.",'best'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",3
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: int, float or {""sqrt"", ""log2""}, default=NoneThe number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... note:: The search for a split does not stop until at least one valid partition of the node samples is found, even if it requires to effectively inspect more than ``max_features`` features.",None
,"random_state random_state: int, RandomState instance or None, default=NoneControls the randomness of the estimator. The features are alwaysrandomly permuted at each split, even if ``splitter`` is set to``""best""``. When ``max_features < n_features``, the algorithm willselect ``max_features`` at random at each split before finding the bestsplit among them. But the best found split may vary across differentruns, even if ``max_features=n_features``. That is the case, if theimprovement of the criterion is identical for several splits and onesplit has to be selected at random. To obtain a deterministic behaviourduring fitting, ``random_state`` has to be fixed to an integer.See :term:`Glossary ` for details.",None
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow a tree with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current 

In [74]:
# 딕셔너리로 파라미터명과 탐색할 값 목록을 지정. 여기서는 DecisionTreeClassifier 모델을 사용한다고 가정.
param_grid = {
    'n_estimators': [100, 200, 300],   # 트리 개수
    'max_depth': [3, 5, 7],            # 트리 최대 깊이
    'min_samples_split': [2, 5, 10]    # 분기를 위한 최소 샘플 수
}
# 3 x 3 x 3 = 총 27가지 조합

In [75]:
# 모델 객체 설정
dt = DecisionTreeClassifier(random_state=42)

# GridSearchCV 객체 설정
grid_dt = GridSearchCV(
    estimator=dt,          # 튜닝할 모델
    param_grid=param_grid, # Step 1에서 정의한 조합
    scoring = 'accuracy',   # 모델의 성능을 평가하는 기준
    cv=3,                  # 교차 검증 개수 설정
    refit=True,            # 최적 파라미터로 전체 데이터 재학습
    n_jobs=-1              # 가능한 모든 CPU 코어 사용
)

# 학습 데이터만 넣는다
grid_dt.fit(train_input, train_target)

ValueError: Invalid parameter 'n_estimators' for estimator DecisionTreeClassifier(max_depth=3, min_samples_split=5, random_state=42). Valid parameters are: ['ccp_alpha', 'class_weight', 'criterion', 'max_depth', 'max_features', 'max_leaf_nodes', 'min_impurity_decrease', 'min_samples_leaf', 'min_samples_split', 'min_weight_fraction_leaf', 'monotonic_cst', 'random_state', 'splitter'].

In [ ]:
# 최적 하이퍼파라미터 조합 확인
print(grid_dt.best_params_)
# 출력 예시: {'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 200}

# 최적 파라미터로 이미 재학습된 모델
best_model = grid_dt.best_estimator_


In [ ]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 2]


In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['박', '현', '웅', '머', '신', '러', '닝']

items = np.array(items).reshape(-1, 1)

oh = OneHotEncoder()
oh.fit(items)
oh_labels = oh.transform(items)

print(oh_labels.toarray())


[[0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]


In [ ]:
import pandas as pd

df = pd.DataFrame({'items':['박', '현', '웅']})
pd.get_dummies(df)

,items_박,items_웅,items_현
0,True,False,False
1,False,False,True
2,False,True,False


In [ ]:
# 군집화 p.431
from sklearn.preprocessing import scale
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

iris = load_iris()
irisDF = pd.DataFrame(data=iris['data'], columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
irisDF.head(3)

,sepal_length,sepal_width,petal_length,petal_width
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2


In [ ]:
km = KMeans(n_clusters=3, init='k-means++', max_iter=300, random_state=42)
km.fit(irisDF)

c:\Users\1724q\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1425: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


,"n_clusters n_clusters: int, default=8The number of clusters to form as well as the number ofcentroids to generate.For an example of how to choose an optimal value for `n_clusters` refer to:ref:`sphx_glr_auto_examples_cluster_plot_kmeans_silhouette_analysis.py`.",3
,"init init: {'k-means++', 'random'}, callable or array-like of shape (n_clusters, n_features), default='k-means++'Method for initialization:* 'k-means++' : selects initial cluster centroids using sampling based on an empirical probability distribution of the points' contribution to the overall inertia. This technique speeds up convergence. The algorithm implemented is ""greedy k-means++"". It differs from the vanilla k-means++ by making several trials at each sampling step and choosing the best centroid among them.* 'random': choose `n_clusters` observations (rows) at random from data for the initial centroids.* If an array is passed, it should be of shape (n_clusters, n_features) and gives the initial centers.* If a callable is passed, it should take arguments X, n_clusters and a random state and return an initialization.For an example of how to use the different `init` strategies, see:ref:`sphx_glr_auto_examples_cluster_plot_kmeans_digits.py`.For an evaluation of the impact of initialization, see the example:ref:`sphx_glr_auto_examples_cluster_plot_kmeans_stability_low_dim_dense.py`.",'k-means++'
,"n_init n_init: 'auto' or int, default='auto'Number of times the k-means algorithm is run with different centroidseeds. The final results is the best output of `n_init` consecutive runsin terms of inertia. Several runs are recommended for sparsehigh-dimensional problems (see :ref:`kmeans_sparse_high_dim`).When `n_init='auto'`, the number of runs depends on the value of init:10 if using `init='random'` or `init` is a callable;1 if using `init='k-means++'` or `init` is an array-like... versionadded:: 1.2 Added 'auto' option for `n_init`... versionchanged:: 1.4 Default value for `n_init` changed to `'auto'`.",'auto'
,"max_iter max_iter: int, default=300Maximum number of iterations of the k-means algorithm for asingle run.",300
,"tol tol: float, default=1e-4Relative tolerance with regards to Frobenius norm of the differencein the cluster centers of two consecutive iterations to declareconvergence.",0.0001
,"verbose verbose: int, default=0Verbosity mode.",0
,"random_state random_state: int, RandomState instance or None, default=NoneDetermines random number generation for centroid initialization. Usean int to make the randomness deterministic.See :term:`Glossary `.",42
,"copy_x copy_x: bool, default=TrueWhen pre-computing distances it is more numerically accurate to centerthe data first. If copy_x is True (default), then the original data isnot modified. If False, the original data is modified, and put backbefore the function returns, but small numerical differences may beintroduced by subtracting and then adding the data mean. Note that ifthe original data is not C-contiguous, a copy will be made even ifcopy_x is False. If the original data is sparse, but not in CSR format,a copy will be made even if copy_x is False.",True
,"algorithm algorithm: {""lloyd"", ""elkan""}, default=""lloyd""K-means algorithm to use. The classical EM-style algorithm is `""lloyd""`.The `""elkan""` variation can be more efficient on some datasets withwell-defined clusters, by using the triangle inequality. However it'smore memory intensive due to the allocation of an extra array of shape`(n_samples, n_clusters)`... versionchanged:: 0.18 Added Elkan algorithm.. versionchanged:: 1.1 Renamed ""full"" to ""lloyd"", and deprecated ""auto"" and ""full"". Changed ""auto"" to use ""lloyd"" instead of ""elkan"".",'lloyd'


In [ ]:
print(km.labels_)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 0 0 0 0 2 0 0 0 0
 0 0 2 2 0 0 0 0 2 0 2 0 2 0 0 2 2 0 0 0 0 0 2 0 0 0 0 2 0 0 0 2 0 0 0 2 0
 0 2]


In [ ]:
irisDF['target'] = iris['target']
irisDF['cluster'] = km.labels_
iris_result = irisDF.groupby(['target', 'cluster'])['sepal_length'].count()
print(iris_result)

target  cluster
0       1          50
1       0           3
        2          47
2       0          36
        2          14
Name: sepal_length, dtype: int64


In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
pca_transformed = pca.fit_transform(iris['data'])

irisDF['pca_x'] = pca_transformed[:, 0]
irisDF['pca_y'] = pca_transformed[:, 1]
irisDF.head(3)

,sepal_length,sepal_width,petal_length,petal_width,target,cluster,pca_x,pca_y
0,5.1,3.5,1.4,0.2,0,1,-2.684126,0.319397
1,4.9,3.0,1.4,0.2,0,1,-2.714142,-0.177001
2,4.7,3.2,1.3,0.2,0,1,-2.888991,-0.144949


In [ ]:
import numpy as np
from sklearn.datasets import make_blobs

X, y = make_blobs(n_samples=200, n_features=2, centers=3, cluster_std=0.8, random_state=42)
print(X.shape, y.shape)

unique, counts = np.unique(y, return_counts=True)
print(unique, counts)

(200, 2) (200,)
[0 1 2] [67 67 66]


In [ ]:
# 실루엣 분석: 각 군집 간의 거리가 얼마나 '효율적으로 분리' 되어 있는지?

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# 간단한 예시 데이터
data = np.array([[1], [2], [3], [4], [5]])

# sklearn의 전처리 클래스는 2차원 데이터로만 작동하므로
# 1
# 2
# 3
# 4
# 5
# (5, 1) 라는 차원을 가진 array를 생성한다.

# StandardScaler 객체 설정
scaler = StandardScaler()

# fit으로 학습 데이터의 평균과 표준편차를 계산해서 scaler 객체 내부에 저장
scaler.fit(data)
print(scaler.mean_)  # = [3.0]
print(scaler.var_ ** 0.5)   # = [1.41421356]

# transform으로 저장된 평균/표준편차를 활용하여 각 값을 변환
scaled = scaler.transform(data)
print(scaled)
# [[-1.41], [-0.71], [0.], [0.71], [1.41]]

[3.]
[1.41421356]
[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [ ]:
train_input = np.array([[100], [200], [300], [400], [500]])
test_input = np.array([[20], [30], [40], [50], [60]])

# StandardScaler 객체 설정
scaler = StandardScaler()

# fit으로 학습 데이터(train_input)의 평균과 표준편차를 계산해서 scaler 객체 내부에 저장
scaler.fit(train_input)
print(scaler.mean_)  # = [300.0]
print(scaler.var_ ** 0.5)   # = [141.42135624]

# transform으로 저장된 평균/표준편차를 활용하여 각 값을 변환
scaled = scaler.transform(test_input)
print(scaled)
# [[-1.97989899], [-1.90918831], [-1.83847763], [-1.76776695], [-1.69705627]]

[300.]
[141.42135624]
[[-1.97989899]
 [-1.90918831]
 [-1.83847763]
 [-1.76776695]
 [-1.69705627]]


In [ ]:
# 만약 테스트 데이터에 fit을 쓴다면?
scaler.fit(test_input)
scaled = scaler.transform(test_input)
print(scaled)
# [[-1.41], [-0.71], [0.], [0.71], [1.41]]

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [ ]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV

# 1. 가상의 데이터 (이미 학습용과 테스트용으로 분리되었다고 가정)
# 데이터 형태: [연소득, 연체횟수]
train_input = np.array([[5000, 1], [3000, 4], [8000, 0], [4500, 2]])
# 1: 상환, 0: 미상환
train_target = np.array([1, 0, 1, 1]) 

test_input = np.array([[4000, 3], [6000, 1]])
test_target = np.array([0, 1])

# 2. scaler 객체 설정
scaler = StandardScaler()

# 빈칸 (A): train 데이터를 기준으로 평균과 표준편차를 학습(fit)시킵니다.
scaler.____(A)____

# 학습된 기준으로 train 데이터를 변환합니다.
train_scaled = scaler.transform(train_input)

# 빈칸 (B): test 데이터를 변환합니다.
test_scaled = ____(B)____

# 3. 모델 및 하이퍼파라미터 설정
dt = DecisionTreeClassifier(random_state=42)
param_grid = {'max_depth': [3, 5, 7], 'min_samples_split': [2, 3, 4]}

# 4. GridSearchCV 적용
# 빈칸 (C): 튜닝할 모델, 파라미터 조합, 그리고 교차 검증 3회를 설정하여 객체를 만듭니다.
grid_dt = GridSearchCV(____(C)____)

# 빈칸 (D): 준비된 GridSearchCV 객체에 스케일링된 훈련 데이터와 타겟 데이터를 넣어 학습시킵니다.
____(D)____

print("최적의 파라미터:", grid_dt.best_params_)
score_df = pd.DataFrame(grid_dt.cv_results_)
score_df

In [ ]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV

# 1. 가상의 데이터 (이미 학습용과 테스트용으로 분리되었다고 가정)
# 데이터 형태: [연소득, 연체횟수]
train_input = np.array([[5000, 1], [3000, 4], [8000, 0], [4500, 2]])
# 1: 상환, 0: 미상환
train_target = np.array([1, 0, 1, 1]) 

test_input = np.array([[4000, 3], [6000, 1]])
test_target = np.array([0, 1])

# 2. scaler 객체 설정
scaler = StandardScaler()

# 빈칸 (A): train 데이터를 기준으로 평균과 표준편차를 학습(fit)시킵니다.
scaler.fit(train_input)

# 학습된 기준으로 train 데이터를 변환합니다.
train_scaled = scaler.transform(train_input)
print(train_scaled)

# 빈칸 (B): test 데이터를 변환합니다.
test_scaled = scaler.transform(test_input)

# 3. 모델 및 하이퍼파라미터 설정
dt = DecisionTreeClassifier(random_state=42)
param_grid = {'max_depth': [3, 5, 7], 'min_samples_split': [2, 3, 4]}

# 4. GridSearchCV 적용
# 빈칸 (C): 튜닝할 모델, 파라미터 조합, 그리고 교차 검증 3회를 설정하여 객체를 만듭니다.
grid_dt = GridSearchCV(estimator=dt, cv=3, n_jobs=-1, param_grid=param_grid)

# 빈칸 (D): 준비된 GridSearchCV 객체에 스케일링된 훈련 데이터와 타겟 데이터를 넣어 학습시킵니다.
grid_dt.fit(train_scaled, train_target)

print("최적의 파라미터:", grid_dt.best_params_)
score_df = pd.DataFrame(grid_dt.cv_results_)
score_df.sort_values('rank_test_score')

[[-0.06884284 -0.50709255]
 [-1.17032826  1.52127766]
 [ 1.5833853  -1.18321596]
 [-0.3442142   0.16903085]]
최적의 파라미터: {'max_depth': 3, 'min_samples_split': 2}


c:\Users\1724q\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:813: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_min_samples_split,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005243,0.002134,0.003740,0.002307,3,2,"{'max_depth': 3, 'min_samples_split': 2}",0.5,1.0,1.0,0.833333,0.235702,1
1,0.005838,0.002805,0.002844,0.001192,3,3,"{'max_depth': 3, 'min_samples_split': 3}",0.5,1.0,1.0,0.833333,0.235702,1
2,0.003950,0.000553,0.002405,0.001012,3,4,"{'max_depth': 3, 'min_samples_split': 4}",0.5,1.0,1.0,0.833333,0.235702,1
3,0.007753,0.002131,0.006468,0.003102,5,2,"{'max_depth': 5, 'min_samples_split': 2}",0.5,1.0,1.0,0.833333,0.235702,1
4,0.007230,0.003585,0.001941,0.000749,5,3,"{'max_depth': 5, 'min_samples_split': 3}",0.5,1.0,1.0,0.833333,0.235702,1
5,0.004069,0.000261,0.002461,0.000534,5,4,"{'max_depth': 5, 'min_samples_split': 4}",0.5,1.0,1.0,0.833333,0.235702,1
6,0.003522,0.000017,0.001948,0.000363,7,2,"{'max_depth': 7, 'min_samples_split': 2}",0.5,1.0,1.0,0.833333,0.235702,1
7,0.005200,0.002456,0.002481,0.000298,7,3,"{'max_depth': 7, 'min_samples_split': 3}",0.5,1.0,1.0,0.833333,0.235702,1
8,0.002140,0.000573,0.001233,0.000719,7,4,"{'max_depth': 7, 'min_samples_split': 4}",0.5,1.0,1.0,0.833333,0.235702,1


In [ ]:
# K-평균을 이용한 붓꽃 데이터 세트 군집화

from sklearn.preprocessing import scale
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

iris = load_iris()
print(iris)
# Pandas의 DataFrame 으로 변환
irisDF = pd.DataFrame(data=iris['data'], columns=['sepal_length', 'sepal_width', 'petal_length',
'petal_width'])
irisDF.head(3)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

,sepal_length,sepal_width,petal_length,petal_width
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2


In [ ]:
kmeans = KMeans(n_clusters=3, init='k-means++', max_iter=300, random_state=42)
# Max_iter = 최대 반복 횟수
kmeans.fit(irisDF)

c:\Users\1724q\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1425: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


,"n_clusters n_clusters: int, default=8The number of clusters to form as well as the number ofcentroids to generate.For an example of how to choose an optimal value for `n_clusters` refer to:ref:`sphx_glr_auto_examples_cluster_plot_kmeans_silhouette_analysis.py`.",3
,"init init: {'k-means++', 'random'}, callable or array-like of shape (n_clusters, n_features), default='k-means++'Method for initialization:* 'k-means++' : selects initial cluster centroids using sampling based on an empirical probability distribution of the points' contribution to the overall inertia. This technique speeds up convergence. The algorithm implemented is ""greedy k-means++"". It differs from the vanilla k-means++ by making several trials at each sampling step and choosing the best centroid among them.* 'random': choose `n_clusters` observations (rows) at random from data for the initial centroids.* If an array is passed, it should be of shape (n_clusters, n_features) and gives the initial centers.* If a callable is passed, it should take arguments X, n_clusters and a random state and return an initialization.For an example of how to use the different `init` strategies, see:ref:`sphx_glr_auto_examples_cluster_plot_kmeans_digits.py`.For an evaluation of the impact of initialization, see the example:ref:`sphx_glr_auto_examples_cluster_plot_kmeans_stability_low_dim_dense.py`.",'k-means++'
,"n_init n_init: 'auto' or int, default='auto'Number of times the k-means algorithm is run with different centroidseeds. The final results is the best output of `n_init` consecutive runsin terms of inertia. Several runs are recommended for sparsehigh-dimensional problems (see :ref:`kmeans_sparse_high_dim`).When `n_init='auto'`, the number of runs depends on the value of init:10 if using `init='random'` or `init` is a callable;1 if using `init='k-means++'` or `init` is an array-like... versionadded:: 1.2 Added 'auto' option for `n_init`... versionchanged:: 1.4 Default value for `n_init` changed to `'auto'`.",'auto'
,"max_iter max_iter: int, default=300Maximum number of iterations of the k-means algorithm for asingle run.",300
,"tol tol: float, default=1e-4Relative tolerance with regards to Frobenius norm of the differencein the cluster centers of two consecutive iterations to declareconvergence.",0.0001
,"verbose verbose: int, default=0Verbosity mode.",0
,"random_state random_state: int, RandomState instance or None, default=NoneDetermines random number generation for centroid initialization. Usean int to make the randomness deterministic.See :term:`Glossary `.",42
,"copy_x copy_x: bool, default=TrueWhen pre-computing distances it is more numerically accurate to centerthe data first. If copy_x is True (default), then the original data isnot modified. If False, the original data is modified, and put backbefore the function returns, but small numerical differences may beintroduced by subtracting and then adding the data mean. Note that ifthe original data is not C-contiguous, a copy will be made even ifcopy_x is False. If the original data is sparse, but not in CSR format,a copy will be made even if copy_x is False.",True
,"algorithm algorithm: {""lloyd"", ""elkan""}, default=""lloyd""K-means algorithm to use. The classical EM-style algorithm is `""lloyd""`.The `""elkan""` variation can be more efficient on some datasets withwell-defined clusters, by using the triangle inequality. However it'smore memory intensive due to the allocation of an extra array of shape`(n_samples, n_clusters)`... versionchanged:: 0.18 Added Elkan algorithm.. versionchanged:: 1.1 Renamed ""full"" to ""lloyd"", and deprecated ""auto"" and ""full"". Changed ""auto"" to use ""lloyd"" instead of ""elkan"".",'lloyd'


In [ ]:
print(len(kmeans.labels_))

150


In [ ]:
irisDF['target'] = iris['target']
irisDF['cluster'] = kmeans.labels_
iris_result = irisDF.groupby(['target', 'cluster'])['sepal_length'].count()
print(iris_result)


target  cluster
0       1          50
1       0           3
        2          47
2       0          36
        2          14
Name: sepal_length, dtype: int64


In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca_transformed = pca.fit_transform(iris['data'])

irisDF['pca_x'] = pca_transformed[:, 0]
irisDF['pca_y'] = pca_transformed[:, 1]
irisDF.head(3)

,sepal_length,sepal_width,petal_length,petal_width,target,cluster,pca_x,pca_y
0,5.1,3.5,1.4,0.2,0,1,-2.684126,0.319397
1,4.9,3.0,1.4,0.2,0,1,-2.714142,-0.177001
2,4.7,3.2,1.3,0.2,0,1,-2.888991,-0.144949
